export const aboutCopy = {
  fa: {
    titleLines: ["همه‌چیز", "لازم نیست", "شبیه نسخه‌ی", "قبل باشد."],
    ledeLines: [
      "یک استودیو برای ساخت",
      "اشیایی که قرار نیست",
      "دقیقاً تکرار شوند.",
    ],
    heroAlt: "ماگ دست‌ساز با لعاب سبزِ چکه‌کرده روی سنگ، در نور عصر",
    scrollHint: "ادامه",
    whyTitleLines: ["چرا رَد", "به‌وجود آمد؟"],
    whyLines: [
      "از این فکر شروع شد",
      "که چیزهایی که دوستشان داریم،",
      "لازم نیست همیشه از قبل",
      "طراحی‌شده، دقیق و قابل تکرار",
      "باشند، گاهی یک عکس می‌بینیم و",
      "دلمان می‌خواهد، نسخه‌ی خودمان",
      "را داشته باشیم؛ گاهی فقط",
      "یک فرم با یک جزئیات در ذهن",
      "می‌ماند.",
    ],
    whyCaptionLines: ["از یک ایده", "یک اثر واقعی."],
    whyAlt: "دست‌هایی در حال شکل‌دادن کاسه روی چرخ سفال",
    founderTitleLines: ["پشت رَد", "من مهدیه‌ام."],
    founderStoryLines: [
      "رَد از ساختن چیزهایی شروع شد",
      "که خودم دلم می‌خواست وجود",
      "داشته باشند؛ چیزهایی که",
      "شاید تصویرشان را جایی دیده بودم،",
      "شاید فقط فُرمشان توی ذهنم",
      "مانده بود.",
    ],
    founderCta: "بیشتر درباره‌ی مهدیه",
    founderAlt: "فیلم کارگاه: دست‌هایی که روی میز کار گل را ورز می‌دهند",
    passageTitleLines: ["چیزی که از", "عبور باقی می‌ماند."],
    passageBodyLines: [
      "هر اثر، رَدِ یک ایده، است.",
      "دست و ماده است. چیزی که",
      "از این عبور می‌ماند؛",
      "همان فرم، همان بافت،",
      "همان نتیجه‌ی ۱/۱ است!",
      "یک شیء واقعی، با تمام",
      "ناقص بودن‌هایش، که همین",
      "ناقص بودن بخشی از هویت",
      "آن است.",
    ],
    passageMark: "رَد",
    passageAlt: "دست‌هایی در حال ورز دادن گل روی میز کار",
    isNotLines: ["رَد", "نیست…"],
    notItems: [
      { lines: ["تولید انبوه"] },
      { lines: ["کنترل همه‌چیز", "تا آخرین میلی‌متر"] },
      { lines: ["کپی دقیق یک نمونه"] },
      { lines: ["کنترل همه‌چیز", "تا آخرین میلی‌متر"] },
      { lines: ["ساختن دوباره‌ی یک اثر"] },
    ],
    notAlt: "کاسه‌ی دست‌ساز با لعاب چکه‌ای روی سنگ",
    findTitleLines: ["حالا", "یک رَد", "پیدا کن."],
    findLedeLines: ["بین رَدهای آماده بچرخ", "و ببین کدومش مال توئه."],
    worksCta: "دیدن آثار",
    stampAlt: "مُهر رَد روی گل",
    customTitleLines: ["رَد خودت", "را بساز."],
    customBodyLines: [
      "با یه عکس، یه فرم، یه ایده",
      "یا حتی فقط یه حس شروع کن.",
      "بقیه‌ش رو با هم جلو می‌بریم.",
    ],
    customCta: "سفارش اختصاصی",
    onceLines: ["هر اثر", "فقط یک‌بار."],
    onceAlt: "فنجان دو دسته‌ی دست‌ساز با شاخه‌ای سبز در نور طبیعی",
    closeTitleLines: ["رَدی که باقی می‌ماند،", "داستان توست."],
    closeBodyLines: [
      "در رَد، هر اثر نتیجه‌ی یک مسیر",
      "منحصربه‌فرد است:",
      "از ایده تا خاک، از دست تا پخت،",
      "و از استودیو تا خانه‌ی تو.",
    ],
  },
  en: {
    titleLines: [
      "Not everything",
      "has to resemble",
      "the version",
      "before it.",
    ],
    ledeLines: [
      "A studio for making",
      "objects that are not meant",
      "to be repeated exactly.",
    ],
    heroAlt: "Handmade mug with a dripping green glaze on stone in late sun",
    scrollHint: "Continue",
    whyTitleLines: ["Why does", "RAD exist?"],
    whyLines: [
      "It began with the thought",
      "that the things we love",
      "do not always have to be",
      "predetermined, exact, and repeatable.",
      "Sometimes we see a photograph",
      "and want a version of our own;",
      "sometimes only a form",
      "or a detail stays",
      "in mind.",
    ],
    whyCaptionLines: ["From an idea", "to a real work."],
    whyAlt: "Hands shaping a bowl on the pottery wheel",
    founderTitleLines: ["Behind RAD,", "I’m Mahdiyeh."],
    founderStoryLines: [
      "RAD started from making things",
      "I wanted to exist;",
      "things I may have seen",
      "an image of somewhere,",
      "or whose form had simply",
      "stayed in my mind.",
    ],
    founderCta: "More about me",
    founderAlt: "Workshop film: hands wedging clay on the workbench",
    passageTitleLines: ["What remains", "after something", "passes."],
    passageBodyLines: [
      "Every work is the trace of an idea,",
      "a hand and a material. What remains",
      "of that passage is",
      "the same form, the same texture,",
      "the same 1/1 result!",
      "a real object, with all",
      "its incompleteness, and that",
      "incompleteness is part of",
      "its identity.",
    ],
    passageMark: "RAD",
    passageAlt: "Hands kneading clay on a workbench",
    isNotLines: ["RAD", "is not…"],
    notItems: [
      { lines: ["mass production"] },
      { lines: ["controlling everything", "to the last millimetre"] },
      { lines: ["a starting point"] },
      { lines: ["a human hand"] },
      { lines: ["a material that sometimes", "has its own opinion."] },
      { lines: ["a 1/1 result"] },
    ],
    notAlt: "Handmade bowl with dripping glaze on stone",
    findTitleLines: ["Now", "find", "a RAD."],
    findLedeLines: [
      "Browse the available works",
      "and see which RAD",
      "stays with you.",
    ],
    worksCta: "See the works",
    stampAlt: "The RAD stamp in clay",
    customTitleLines: ["Make your", "own RAD."],
    customBodyLines: [
      "Begin with a photo, a form, an idea.",
      "Or even a feeling.",
      "We’ll make your version",
      "together.",
    ],
    customCta: "Custom order",
    onceLines: ["Each work,", "only once."],
    onceAlt: "Handmade two-handled cup with a green sprig in natural light",
    closeTitleLines: ["The RAD that remains", "is your story."],
    closeBodyLines: [
      "At RAD, every work is the result of",
      "a unique path:",
      "from idea to clay, from hand to firing,",
      "and from the studio to your home.",
    ],
  },
} as const;
