export const aboutCopy = {
  fa: {
    title: "همه‌چیز لازم نیست شبیه نسخه‌ی قبل باشد.",
    lede: "یک استودیو برای ساخت اشیایی که قرار نیست دقیقاً تکرار شوند.",
    openingAlt: "میز کار رَد با ابزار و یک فرم دست‌ساز در نور طبیعی",
    whyTitle: "چرا رَد به‌وجود آمد؟",
    why: [
      "رَد از این فکر شروع شد که چیزهایی که دوستشان داریم، لازم نیست همیشه از قبل طراحی‌شده، دقیق و قابل تکرار باشند. گاهی یک عکس می‌بینیم و دلمان می‌خواهد نسخه‌ی خودمان را داشته باشیم؛ گاهی فقط یک فرم یا یک جزئیات در ذهن می‌ماند.",
      "رَد جایی‌ست برای تبدیل همین چیزها به یک شیء واقعی؛ نه برای کپی‌کردن دقیق یک تصویر، برای دیدن اینکه وقتی یک ایده از ذهن، دست و ماده رد می‌شود، آخرش چه شکلی پیدا می‌کند. و چون این مسیر هیچ‌وقت دقیقاً دوبار اتفاق نمی‌افتد، هر اثر فقط یک نسخه دارد.",
    ],
    whyAlt: "کاسه‌ی نپخته با لبه‌ای نامنظم و باقی‌مانده‌ی گل روی میز",
    founderTitle: "پشت رَد",
    founderLead: "من مهدیه‌ام.",
    founderStory:
      "رَد از ساختن چیزهایی شروع شد که خودم دلم می‌خواست وجود داشته باشند؛ چیزهایی که شاید تصویرشان را جایی دیده بودم، شاید فقط فرمشان توی ذهنم مانده بود.",
    founderClose: "شروعش با سفال بود، ولی قرار نیست همان‌جا بماند.",
    founderAlt: "دست‌هایی در حال کار روی چرخ سفال، با گل روی پوست",
    nameTitle: "رَد",
    nameLine: "چیزی که از عبور باقی می‌ماند.",
    traceAlt: "لبه‌ی نامنظم و رد لعاب روی یک کاسه‌ی تمام‌شده",
    isNot: "رَد نیست",
    is: "رَد هست",
    notItems: [
      "کپی بی‌نقص یک عکس",
      "تولید انبوه",
      "کنترل همه‌چیز تا آخرین میلی‌متر",
    ],
    isItems: [
      "یک نقطه‌ی شروع",
      "دست آدم",
      "ماده‌ای که گاهی نظر خودش را دارد",
      "یک نتیجه‌ی ۱/۱",
    ],
    finalTitle: "حالا یک رَد پیدا کن.",
    worksTitle: "آثار موجود",
    worksBody: "رَدی را پیدا کن که منتظر آدم خودش است.",
    worksCta: "دیدن آثار",
    customTitle: "رَد خودت",
    customBody: "با یک عکس، فرم، ایده یا حتی یک حس شروع کن.",
    customCta: "شروع یک رَد",
  },
  en: {
    title: "Not everything has to resemble the version before it.",
    lede: "A studio for making objects that are not meant to be repeated exactly.",
    openingAlt: "RAD's workbench, tools, and a handmade form in natural light",
    whyTitle: "Why does RAD exist?",
    why: [
      "RAD began with the thought that the things we love do not always have to be predetermined, exact, and repeatable. Sometimes we see a photograph and want a version of our own; sometimes only a form or a small detail stays with us.",
      "RAD is a place for turning those fragments into a real object—not to copy an image exactly, but to discover what an idea becomes after passing through a mind, a hand, and a material. Because that passage never happens twice in the same way, every work exists only once.",
    ],
    whyAlt: "An unfired bowl with an irregular rim and leftover clay on the table",
    founderTitle: "Behind RAD",
    founderLead: "I’m Mahdiyeh.",
    founderStory:
      "RAD started from making things I wanted to exist; things I may have seen an image of somewhere, or whose form had simply stayed in my mind.",
    founderClose: "It began with clay, but it is not meant to stay there.",
    founderAlt: "Hands working a bowl on the wheel, clay still on the skin",
    nameTitle: "RAD",
    nameLine: "What remains after something passes.",
    traceAlt: "An irregular rim and glaze trace on a finished bowl",
    isNot: "RAD is not",
    is: "RAD is",
    notItems: [
      "a perfect copy of a photograph",
      "mass production",
      "controlling everything down to the last millimetre",
    ],
    isItems: [
      "a starting point",
      "a human hand",
      "a material that sometimes has its own opinion",
      "a 1/1 result",
    ],
    finalTitle: "Now find a RAD.",
    worksTitle: "Available works",
    worksBody: "Find the RAD that is waiting for its person.",
    worksCta: "See the works",
    customTitle: "Your RAD",
    customBody: "Begin with a photograph, a form, an idea, or even a feeling.",
    customCta: "Start a RAD",
  },
} as const;
