export const designerCopy = {
  fa: {
    stepsLabel: "مراحل سفارش",
    next: "ادامه",
    back: "بازگشت",
    ideaTitle: "چی توی ذهنت داری؟",
    ideaHelp:
      "هرجوری راحتی برامون تعریفش کن؛ می‌تونی بنویسی، عکس بدی یا ویس بفرستی.",
    ideaLabel: "ایده‌ت رو بگو",
    ideaPlaceholder:
      "مثلاً یک کاسه با فرم خاص و رنگ خاکی مات، یا هر ایده‌ای که در ذهن داری…",
    ideaAttachLabel: "افزودن مرجع",
    uploadTitle: "عکس داری؟ اینجا بفرست",
    uploadHint: "تا ۴ تصویر، هرکدام تا ۱۰ مگابایت",
    addPhoto: "افزودن عکس",
    addDrawing: "افزودن طرح دستی",
    addVoice: "ویس بفرست",
    addAnotherPhoto: "افزودن تصویر دیگر",
    removePhoto: "حذف تصویر",
    attached: "پیوست شد",
    cardEmpty: "هنوز چیزی اضافه نکردی.",
    cardNote: "این فقط مرجعه؛ قرار نیست نتیجه دقیقاً همین بشه.",
    formTitle: "چی بسازیم؟",
    formHelp: "نزدیک‌ترین گزینه به چیزی که توی ذهنته رو انتخاب کن.",
    useLabel: "قراره کجا یا برای چی استفاده بشه؟",
    detailsTitle: "یه کم بیشتر بگو",
    detailsHelp: "این چندتا جزئیات کمک می‌کنه بهتر بفهمیم چی می‌خوای.",
    sizeLabel: "اندازه‌ی حدودی",
    exactLabel: "اگه اندازه‌ی دقیق داری",
    length: "طول",
    width: "عرض",
    height: "ارتفاع",
    unit: "سانت",
    colorsLabel: "چه رنگی باشه؟",
    colorsHint: "تا سه رنگ",
    colorNoteLabel: "رنگ خاصی توی ذهنت هست؟ بنویس",
    colorNotePlaceholder: "مثلاً سبز زیتونی مات…",
    fidelityLabel: "چقدر شبیه مرجعت باشه؟",
    fidelityLow: "نزدیک به مرجع",
    fidelityLowHint: "(مشابه تصویر)",
    fidelityHigh: "آزاد",
    fidelityHighHint: "(با خلاقیت رَد)",
    fidelityFaithful: "نزدیک به مرجع",
    fidelityHand: "شبیهش باشه، ولی دستمون باز باشه",
    fidelityFree: "مرجع فقط ایده بده؛ بقیه‌ش با رَد",
    planTitle: "بودجه و زمانی که داری",
    planHelp:
      "حدود بودجه و زمانی که داری رو بگو تا بدونیم چه پیشنهادی برات مناسبه.",
    budgetLabel: "حدوداً چقدر می‌خوای هزینه کنی؟",
    timelineLabel: "کی بهش نیاز داری؟",
    dateLabel: "چه روزی باید دستت باشه؟",
    datePlaceholder: "مثلاً ۲۰ آبان، برای تولد",
    reviewTitle: "یه نگاه آخر",
    reviewHelp:
      "یه بار چک کن همه‌چی همونیه که می‌خواستی. بعدش می‌فرستیش برای ما.",
    summaryTitle: "چیزی که برامون فرستادی",
    summaryEdit: "ویرایش",
    summaryIdea: "ایده",
    summaryForm: "فرم",
    summarySize: "اندازه",
    summaryColors: "رنگ",
    summaryFidelity: "وفاداری به مرجع",
    summaryBudget: "بودجه",
    summaryTime: "زمان",
    summaryNone: "—",
    ideaFromPhoto: "از روی تصویر ارسال‌شده",
    ideaFromSketch: "از روی طرح دستی",
    ideaFromVoice: "یادداشت صوتی",
    nextTitle: "بعدش چی می‌شه؟",
    notesTitle: "قبل از فرستادن اینا رو بدون",
    agreeLink: "قوانین و شرایط سفارش اختصاصی",
    agreeAfter: "را می‌پذیرم.",
    submit: "فرستادن ایده",
    submitNote:
      "فرستادن ایده هیچ هزینه‌ای نداره. اگه قابل ساخت باشه، قیمت و زمان رو بهت می‌گیم.",
    sentTitle: "ایده‌ت رسید :)",
    sentBody:
      "نگاهش می‌کنیم ببینیم چطور می‌شه ساختش. بعد با قیمت و زمان دقیق برمی‌گردیم پیشت.",
    sentFollow: "دیدن وضعیت سفارش",
    sentAnother: "یه ایده‌ی دیگه دارم",
    sentHome: "بازگشت به خانه",
    conceptForm: "فرم",
    conceptUse: "کاربری",
    conceptSize: "اندازه",
    conceptColors: "رنگ",
    conceptFidelity: "وفاداری به مرجع",
    conceptTime: "زمان",
    conceptVoice: "یک یادداشت صوتی همراه است.",
    fallbackTitle: "ایده‌ی استودیو",
  },
  en: {
    stepsLabel: "Order steps",
    next: "Continue",
    back: "Back",
    ideaTitle: "What do you have in mind?",
    ideaHelp:
      "Share your idea with us. The more you tell us, the better we can turn it into something real.",
    ideaLabel: "Describe the idea",
    ideaPlaceholder:
      "e.g. a bowl with an unusual form in a matte earthy colour, or any idea you have…",
    ideaAttachLabel: "Add a reference",
    uploadTitle: "Add a photo or reference image",
    uploadHint: "Up to 4 images, 10 MB each",
    addPhoto: "Add photo",
    addDrawing: "Add a sketch",
    addVoice: "Voice note",
    addAnotherPhoto: "Add another image",
    removePhoto: "Remove image",
    attached: "attached",
    cardEmpty: "Nothing on the card yet.",
    cardNote: "This isn’t the final piece; it’s where we start.",
    formTitle: "What should we make?",
    formHelp: "Choose a category.",
    useLabel: "Use or style",
    detailsTitle: "A few details",
    detailsHelp:
      "This helps us design and make the piece more precisely, closer to your taste.",
    sizeLabel: "Approximate size",
    exactLabel: "Exact dimensions (optional)",
    length: "Length",
    width: "Width",
    height: "Height",
    unit: "cm",
    colorsLabel: "Colour",
    colorsHint: "Up to three",
    colorNoteLabel: "Or describe the colour (optional)",
    colorNotePlaceholder: "e.g. matte olive green…",
    fidelityLabel: "How close to the reference?",
    fidelityLow: "Close to reference",
    fidelityLowHint: "(like the image)",
    fidelityHigh: "Free",
    fidelityHighHint: "(RAD’s creativity)",
    fidelityFaithful: "Close to the reference",
    fidelityHand: "Close, with the maker’s hand",
    fidelityFree: "Free, with RAD’s creativity",
    planTitle: "Budget and time",
    planHelp:
      "Pick a rough range and we’ll shape the best proposal for your time and budget.",
    budgetLabel: "Budget range",
    timelineLabel: "When do you need it?",
    dateLabel: "Which date?",
    datePlaceholder: "e.g. 10 November, for a birthday",
    reviewTitle: "Before you send",
    reviewHelp:
      "Take one more look. Once you send it, we read the idea and get back to you with a proposal.",
    summaryTitle: "Request summary",
    summaryEdit: "Edit",
    summaryIdea: "Idea",
    summaryForm: "Form",
    summarySize: "Size",
    summaryColors: "Colour",
    summaryFidelity: "Fidelity",
    summaryBudget: "Budget",
    summaryTime: "Time",
    summaryNone: "—",
    ideaFromPhoto: "From the uploaded image",
    ideaFromSketch: "From the sketch",
    ideaFromVoice: "Voice note",
    nextTitle: "What happens next?",
    notesTitle: "Good to know before sending",
    agreeLink: "custom order terms",
    agreeAfter: "",
    submit: "Send idea for review",
    submitNote: "Sending an idea is free; you only pay after final approval.",
    sentTitle: "Your request has reached RAD.",
    sentBody:
      "First we check whether the idea can be made; then we agree the price and exact timing with you.",
    sentFollow: "Follow your request",
    sentAnother: "Send another idea",
    sentHome: "Back to home",
    conceptForm: "Form",
    conceptUse: "Use",
    conceptSize: "Size",
    conceptColors: "Colours",
    conceptFidelity: "Fidelity to reference",
    conceptTime: "Time",
    conceptVoice: "A voice note is attached.",
    fallbackTitle: "Studio idea",
  },
} as const;
