export const productCardCopy = {
  fa: {
    by: "اثری از",
    maker: "استودیو رَد",
    popular: "محبوب",
    inBag: "در کیسه",
    studio: "RĀD STUDIO",
    scan: "کد QR و شناسنامه‌ی",
    views: "نماهای اثر",
    view: "نما",
    plate: "نمای آرشیوی",
    moreViews: "نمای دیگر در صفحه‌ی اثر",
    carousel: "آثار",
    previous: "آثار قبلی",
    next: "آثار بعدی",
    goTo: "رفتن به اثر",
  },
  en: {
    by: "A work by",
    maker: "RAD Studio",
    popular: "Popular",
    inBag: "In your bag",
    studio: "RĀD STUDIO",
    scan: "QR code and record for",
    views: "Views of the work",
    view: "View",
    plate: "Archive plate",
    moreViews: "more views on the work's page",
    carousel: "Works",
    previous: "Previous works",
    next: "Next works",
    goTo: "Go to work",
  },
} as const;
