import type {LocaleCopy, MakingCommission, QuoteProposal} from "@/components/making/type";

function loc(fa: string, en: string): LocaleCopy {
  return { fa, en };
}

const now = Date.now();
const day = 24 * 60 * 60 * 1000;

const saharQuote: QuoteProposal = {
  specification: loc(
    "کاسه سرامیکی متوسط با لبه نامتقارن، بدنه سنگ‌رس تهران، لعاب G-17 در بازه خاکستری‌سبز تا کهربایی گرم. کاربرد: سفره و نگاه روزمره. اجازه غافلگیری: دست هنرمند.",
    "A medium ceramic bowl with an asymmetric rim, Tehran stoneware body, glaze G-17 in a grey-green to warm amber range. Intended use: daily table and looking. Permission for surprise: artist’s hand.",
  ),
  artistName: "سحر میرزایی",
  priceToman: 18_400_000,
  priceUsd: 220,
  depositToman: 9_200_000,
  depositUsd: 110,
  completionWindow: loc("چهار تا شش هفته از بیعانه", "Four to six weeks from deposit"),
  includedRevisions: 1,
  cancellationRules: loc(
    "پیش از کوره، بیعانه پس از کسر مواد و زمان مصرف‌شده قابل استرداد است. پس از ورود به کوره، فرم و لعاب برگشت‌ناپذیرند و بیعانه قابل بازگشت نیست.",
    "Before the kiln, the deposit is refundable minus consumed material and time. Once the piece enters the kiln, form and glaze cannot be changed and the deposit is not refundable.",
  ),
  createdAt: now - 12 * day,
};

export const seedCommissions: MakingCommission[] = [
  {
    id: "RAD-M-1405-17",
    title: loc("کاسه خانه‌تنگی", "Homesickness bowl"),
    customerName: "مهدیه نوروزی",
    artistName: "سحر میرزایی",
    brief: {
      concept: "کاسه‌ای که حس خانه‌تنگی حیاط مادربزرگ را نگه دارد؛ لبه آرام، خاکی، نه تزئینی.",
      dimensions: "متوسط — حدود ۱۸ سانتی‌متر دهانه",
      material: "سنگ‌رس تهران، سطح مات",
      intendedUse: "سفره روزمره و نگاه روی طاقچه",
      budget: "۱۰ تا ۲۰ میلیون",
      permission: "دست هنرمند",
      category: "ceramics",
    },
    stage: "pre_kiln",
    nextActor: "customer",
    estimatedCompletion: now + 18 * day,
    deadlineAt: now + 2 * day,
    createdAt: now - 21 * day,
    updatedAt: now - 1 * day,
    kilnLocked: false,
    quote: saharQuote,
    approvedSnapshot: {
      quote: saharQuote,
      brief: {
        concept: "کاسه‌ای که حس خانه‌تنگی حیاط مادربزرگ را نگه دارد؛ لبه آرام، خاکی، نه تزئینی.",
        dimensions: "متوسط — حدود ۱۸ سانتی‌متر دهانه",
        material: "سنگ‌رس تهران، سطح مات",
        intendedUse: "سفره روزمره و نگاه روی طاقچه",
        budget: "۱۰ تا ۲۰ میلیون",
        permission: "دست هنرمند",
        category: "ceramics",
      },
      approvedAt: now - 11 * day,
    },
    payments: [
      {
        id: "pay-17-d",
        kind: "deposit",
        status: "paid",
        amountToman: 9_200_000,
        amountUsd: 110,
        at: now - 11 * day,
      },
      {
        id: "pay-17-b",
        kind: "balance",
        status: "due",
        amountToman: 9_200_000,
        amountUsd: 110,
      },
    ],
    changeRequests: [],
    preKiln: {
      dimensions: loc("دهانه ۱۷.۶ سانتی‌متر، بلندی ۸.۲ سانتی‌متر", "Rim 17.6 cm, height 8.2 cm"),
      glazeCode: "G-17",
      glazeName: loc("خاکستر زیتونی روی سنگ‌رس", "Olive ash over stoneware"),
      colorRange: loc(
        "از سبز خاکستری خنک تا کهربایی گرم؛ لبه ممکن است روشن‌تر بسوزد.",
        "Cool grey-green to warm amber; the rim may fire lighter.",
      ),
      testTileNote: loc(
        "کاشی آزمایشی همین دسته لعاب، پخت قبلی استودیو — مرجع است نه وعده تطابق.",
        "A photographed test tile from this glaze batch, previous studio firing — a reference, not a colour promise.",
      ),
      createdAt: now - 1 * day,
    },
    updates: [
      {
        id: "u-17-1",
        stageId: "making",
        note: loc("فرم روی چرخ گرفته شد؛ لبه کمی به داخل برگشت.", "Thrown on the wheel; the rim turns slightly inward."),
        photoKind: "forming",
        requiresApproval: false,
        createdAt: now - 8 * day,
      },
      {
        id: "u-17-2",
        stageId: "pre_kiln",
        note: loc("فرم خشک و پاک شده؛ آماده پیشنهاد لعاب.", "Form dried and cleaned; ready for the glaze proposal."),
        photoKind: "cleaned",
        requiresApproval: true,
        createdAt: now - 1 * day,
      },
      {
        id: "u-17-3",
        stageId: "pre_kiln",
        note: loc("کاشی آزمایشی G-17 از پخت پیشین.", "G-17 test tile from a previous firing."),
        photoKind: "tile",
        requiresApproval: false,
        createdAt: now - 1 * day,
      },
    ],
    messages: [
      {
        id: "m-17-1",
        stageId: "design_submitted",
        author: "customer",
        body: loc(
          "می‌خواهم وقتی کاسه را برمی‌دارم، حیاط را به یاد بیاورم؛ نه یک نقش تزئینی.",
          "I want the bowl to recall a courtyard when I lift it — not a decorative motif.",
        ),
        createdAt: now - 21 * day,
      },
      {
        id: "m-17-2",
        stageId: "feasibility",
        author: "artist",
        body: loc(
          "فرم ممکن است. لعاب را روی سنگ‌رس همین دسته آزمایش می‌کنم تا بازه رنگ مشخص شود.",
          "The form is possible. I will test the glaze on this clay batch so the colour range is honest.",
        ),
        createdAt: now - 19 * day,
      },
      {
        id: "m-17-3",
        stageId: "pre_kiln",
        author: "artist",
        body: loc(
          "رنگ دقیقاً همین نخواهد بود. آتش حرف آخر را می‌زند.",
          "It will not be exactly this colour. The kiln keeps the last word.",
        ),
        createdAt: now - 1 * day,
      },
    ],
    audit: [
      {
        id: "a-17-1",
        at: now - 21 * day,
        actor: "customer",
        stageId: "design_submitted",
        action: loc("طرح ارسال شد", "Design submitted"),
      },
      {
        id: "a-17-2",
        at: now - 19 * day,
        actor: "artist",
        stageId: "feasibility",
        action: loc("طرح تأیید شد", "Design approved"),
      },
      {
        id: "a-17-3",
        at: now - 12 * day,
        actor: "artist",
        stageId: "quote",
        action: loc("پیشنهاد قیمت ارسال شد", "Quote sent"),
      },
      {
        id: "a-17-4",
        at: now - 11 * day,
        actor: "customer",
        stageId: "approval_deposit",
        action: loc("مشخصات تأیید و بیعانه پرداخت شد", "Specification accepted and deposit paid"),
      },
      {
        id: "a-17-5",
        at: now - 1 * day,
        actor: "artist",
        stageId: "pre_kiln",
        action: loc("ایستگاه پیش از کوره باز شد", "Pre-kiln checkpoint opened"),
      },
    ],
    internalNotes: [
      {
        id: "n-17-1",
        stageId: "making",
        author: "artist",
        body: loc(
          "لبه را کمی ضخیم‌تر نگه دار؛ مشتری کاربرد روزانه دارد.",
          "Keep the rim a little thicker; the customer will use this daily.",
        ),
        createdAt: now - 8 * day,
        internal: true,
      },
    ],
  },
  {
    id: "RAD-M-1405-22",
    title: loc("دیوارکوب کوچه لوت", "Lut alley wall piece"),
    customerName: "رها احمدی",
    artistName: "سحر میرزایی",
    brief: {
      concept: "دیوارکوب سرامیکی با خطوط افقی شبیه حرارت کویر؛ شن و سایه.",
      dimensions: "بزرگ",
      material: "سفال و سرامیک، سطح خام",
      intendedUse: "دیوار ورودی خانه",
      budget: "بیش از ۲۰ میلیون",
      permission: "ماده تصمیم می‌گیرد",
      category: "ceramics",
    },
    stage: "design_submitted",
    nextActor: "artist",
    estimatedCompletion: now + 45 * day,
    deadlineAt: now + 1 * day,
    createdAt: now - 2 * day,
    updatedAt: now - 2 * day,
    kilnLocked: false,
    messages: [
      {
        id: "m-22-1",
        stageId: "design_submitted",
        author: "customer",
        body: loc(
          "نمی‌خواهم نقشه کویر باشد؛ می‌خواهم حرارت را حس کنم.",
          "I do not want a map of the desert. I want the heat to be felt.",
        ),
        createdAt: now - 2 * day,
      },
    ],
    changeRequests: [],
    updates: [
      {
        id: "u-22-0",
        stageId: "design_submitted",
        note: loc("تصویر تولیدشده همراه طرح ارسال شد.", "The generated image was submitted with the design."),
        photoKind: "concept",
        requiresApproval: false,
        createdAt: now - 2 * day,
      },
    ],
    payments: [],
    audit: [
      {
        id: "a-22-1",
        at: now - 2 * day,
        actor: "customer",
        stageId: "design_submitted",
        action: loc("طرح ارسال شد", "Design submitted"),
      },
    ],
    internalNotes: [],
  },
  {
    id: "RAD-M-1404-09",
    title: loc("ظرف زیتونی شماره ۰۹", "Olive vessel 09"),
    customerName: "کیمیا رضایی",
    artistName: "سحر میرزایی",
    brief: {
      concept: "ظرفی آرام برای شاخه‌های کوتاه؛ سطح مات زیتونی.",
      dimensions: "کوچک",
      material: "پرسلان شنی",
      intendedUse: "طاقچه و شاخه",
      budget: "تا ۱۰ میلیون",
      permission: "وفادار به طرح",
      category: "ceramics",
    },
    stage: "complete",
    nextActor: "none",
    estimatedCompletion: now - 40 * day,
    createdAt: now - 90 * day,
    updatedAt: now - 38 * day,
    tracking: "RAD-POST-8821",
    kilnLocked: true,
    quote: {
      ...saharQuote,
      priceToman: 9_600_000,
      priceUsd: 115,
      depositToman: 4_800_000,
      depositUsd: 58,
      createdAt: now - 80 * day,
    },
    approvedSnapshot: {
      quote: {
        ...saharQuote,
        priceToman: 9_600_000,
        priceUsd: 115,
        depositToman: 4_800_000,
        depositUsd: 58,
        createdAt: now - 80 * day,
      },
      brief: {
        concept: "ظرفی آرام برای شاخه‌های کوتاه؛ سطح مات زیتونی.",
        dimensions: "کوچک",
        material: "پرسلان شنی",
        intendedUse: "طاقچه و شاخه",
        budget: "تا ۱۰ میلیون",
        permission: "وفادار به طرح",
        category: "ceramics",
      },
      approvedAt: now - 78 * day,
    },
    payments: [
      {
        id: "pay-09-d",
        kind: "deposit",
        status: "paid",
        amountToman: 4_800_000,
        amountUsd: 58,
        at: now - 78 * day,
      },
      {
        id: "pay-09-b",
        kind: "balance",
        status: "paid",
        amountToman: 4_800_000,
        amountUsd: 57,
        at: now - 42 * day,
      },
    ],
    changeRequests: [],
    preKiln: {
      dimensions: loc("بلندی ۱۴ سانتی‌متر", "Height 14 cm"),
      glazeCode: "G-04",
      glazeName: loc("زیتون مات", "Matte olive"),
      colorRange: loc("زیتون خاکی تا قهوه‌ای گرم", "Earthy olive to warm brown"),
      testTileNote: loc("کاشی آزمایشی G-04", "G-04 test tile"),
      createdAt: now - 55 * day,
    },
    firing: {
      firingNote: loc("پخت مخروط ۶، کاهش ملایم.", "Cone 6, gentle reduction."),
      finishingNote: loc("پایه سنگ‌زنی شد؛ امضا زیر اثر.", "Foot stoned; signed underneath."),
      qcNote: loc("در بازه تأییدشده. یک لکه آهن روی شانه مانده است.", "Within the approved range. An iron speck remains on the shoulder."),
      unexpected: false,
      createdAt: now - 44 * day,
    },
    updates: [
      {
        id: "u-09-1",
        stageId: "making",
        note: loc("فرم گرفته شد.", "Form thrown."),
        photoKind: "forming",
        requiresApproval: false,
        createdAt: now - 70 * day,
      },
      {
        id: "u-09-2",
        stageId: "reveal",
        note: loc("اثر تمام شد.", "The piece is finished."),
        photoKind: "finished",
        requiresApproval: false,
        createdAt: now - 42 * day,
      },
      {
        id: "u-09-3",
        stageId: "shipping",
        note: loc("بسته‌بندی دو لایه با conservator wrap.", "Double-wrapped for transit."),
        photoKind: "packed",
        requiresApproval: false,
        createdAt: now - 38 * day,
      },
    ],
    messages: [
      {
        id: "m-09-1",
        stageId: "reveal",
        author: "artist",
        body: loc(
          "لکه آهن را نگه داشتم؛ بخشی از رفتار همین خاک است.",
          "I kept the iron speck. It belongs to this clay.",
        ),
        createdAt: now - 42 * day,
      },
    ],
    audit: [
      {
        id: "a-09-1",
        at: now - 90 * day,
        actor: "customer",
        stageId: "design_submitted",
        action: loc("طرح ارسال شد", "Design submitted"),
      },
      {
        id: "a-09-2",
        at: now - 78 * day,
        actor: "customer",
        stageId: "approval_deposit",
        action: loc("بیعانه پرداخت شد", "Deposit paid"),
      },
      {
        id: "a-09-3",
        at: now - 50 * day,
        actor: "customer",
        stageId: "pre_kiln",
        action: loc("کوره تأیید شد", "Kiln approved"),
      },
      {
        id: "a-09-4",
        at: now - 42 * day,
        actor: "customer",
        stageId: "reveal",
        action: loc("مانده حساب پرداخت شد", "Balance paid"),
      },
      {
        id: "a-09-5",
        at: now - 38 * day,
        actor: "artist",
        stageId: "shipping",
        action: loc("ارسال شد", "Shipped"),
      },
    ],
    internalNotes: [],
  },
];
