export const designerCopy = {
  fa: {
    ideaTitle: "چی توی ذهنت داری؟",
    ideaHelp: "لازم نیست کامل باشد. یک جمله، یک عکس، یک خط کج یا یک صدا کافی است.",
    ideaLabel: "توضیح ایده",
    addPhoto: "افزودن عکس",
    addDrawing: "افزودن طرح دستی",
    addVoice: "توضیح صوتی",
    attached: "پیوست شد",
    formTitle: "می‌خواهی چه چیزی بسازیم؟",
    formHelp: "هرچند گزینه که به ایده‌ات نزدیک است. لازم نیست دقیق باشد.",
    detailsTitle: "کمی جزئیات",
    detailsHelp: "همه‌ی این‌ها تقریبی‌اند؛ دقیقش را بعداً با هم مشخص می‌کنیم.",
    sizeLabel: "حدوداً چه اندازه‌ای؟",
    sizeSmall: "کوچک",
    sizeLarge: "بزرگ",
    exactSizeLabel: "اگر اندازه‌ی دقیق را می‌دانی (اختیاری)",
    exactSizePlaceholder: "مثلاً ارتفاع ۱۲، دهانه‌ی ۹ سانتی‌متر",
    colorsLabel: "چه رنگ‌هایی دوست داری؟",
    colorsHelp: "تا سه رنگ — اختیاری",
    customColor: "رنگ دیگر",
    removeColor: "حذف رنگ",
    fidelityLabel: "چقدر به مرجع وفادار باشد؟",
    fidelityLow: "کاملاً شبیه",
    fidelityHigh: "آزاد",
    fidelityFaithful: "تا جای ممکن نزدیک به مرجع",
    fidelityHand: "نزدیک به مرجع، با دست سازنده",
    fidelityFree: "آزاد؛ غافلگیرم کن",
    planTitle: "بودجه و زمان",
    budgetLabel: "برای این سفارش چقدر در نظر گرفته‌ای؟",
    budgetHelp: "فقط کمک می‌کند پیشنهاد مناسب‌تری بدهیم.",
    timelineLabel: "کِی لازمش داری؟",
    dateLabel: "چه تاریخی؟",
    datePlaceholder: "مثلاً ۲۰ آبان، برای تولد",
    reviewTitle: "پیش از ارسال درخواست",
    reviewHelp: "یک نگاه آخر به ایده‌ات و به اینکه بعد از ارسال چه اتفاقی می‌افتد.",
    summaryTitle: "خلاصه‌ی ایده",
    summaryIdea: "ایده",
    summaryForm: "فرم",
    summarySize: "اندازه",
    summaryColors: "رنگ",
    summaryFidelity: "وفاداری",
    summaryBudget: "بودجه",
    summaryTime: "زمان",
    summaryEdit: "ویرایش",
    summaryNone: "—",
    attachPhotos: "{count} عکس",
    attachSketch: "طرح دستی",
    attachVoice: "یادداشت صوتی",
    nextTitle: "بعد از ارسال چه می‌شود؟",
    notesTitle: "چند نکته",
    rulesLink: "همه‌ی نکته‌های سفارش اختصاصی",
    agree: "نکته‌ها و شرایط سفارش اختصاصی را خواندم و می‌پذیرم.",
    agreeNote: "نسخه‌ای از شرایط که امروز می‌پذیری، همراه سفارشت ذخیره می‌شود.",
    fullTerms: "متن کامل شرایط سفارش اختصاصی",
    submit: "ایده را برای بررسی بفرست",
    submitNote: "فرستادن ایده هزینه‌ای ندارد؛ پرداخت فقط بعد از تأیید پیشنهاد رَد است.",
    talkFirst: "هنوز مطمئن نیستی ایده‌ات ساختنی است؟",
    talkFirstLink: "اول با ما حرف بزن.",
    sentTitle: "درخواستت به رَد رسید.",
    sentBody:
      "اول بررسی می‌کنیم ایده ساختنی است یا نه؛ بعد قیمت و زمان دقیق را با تو هماهنگ می‌کنیم.",
    sentFollow: "دنبال‌کردن درخواست",
    sentAnother: "یک ایده‌ی دیگر",
    cardForm: "فرم",
    cardSize: "اندازه",
    cardBudget: "بودجه",
    cardTime: "زمان",
    cardFidelity: "وفاداری به مرجع",
    conceptForm: "فرم",
    conceptSize: "اندازه",
    conceptColors: "رنگ",
    conceptFidelity: "وفاداری به مرجع",
    conceptTime: "زمان",
    conceptVoice: "یک یادداشت صوتی همراه است.",
    fallbackTitle: "ایده‌ی استودیو",
  },
  en: {
    ideaTitle: "What do you have in mind?",
    ideaHelp: "It doesn’t have to be complete. A sentence, a photo, a wobbly line or a voice note is enough.",
    ideaLabel: "Describe the idea",
    addPhoto: "Add photo",
    addDrawing: "Add drawing",
    addVoice: "Voice description",
    attached: "attached",
    formTitle: "What would you like us to make?",
    formHelp: "Pick whatever is close to your idea. It doesn’t need to be exact.",
    detailsTitle: "A few details",
    detailsHelp: "All of this is approximate; we settle the exact details together later.",
    sizeLabel: "Roughly what size?",
    sizeSmall: "Small",
    sizeLarge: "Large",
    exactSizeLabel: "If you know the exact size (optional)",
    exactSizePlaceholder: "e.g. 12 cm tall, 9 cm opening",
    colorsLabel: "Which colours do you like?",
    colorsHelp: "Up to three — optional",
    customColor: "Other colour",
    removeColor: "Remove colour",
    fidelityLabel: "How close to the reference should it be?",
    fidelityLow: "Exactly like it",
    fidelityHigh: "Free",
    fidelityFaithful: "As close to the reference as possible",
    fidelityHand: "Close, with the maker’s hand",
    fidelityFree: "Free — surprise me",
    planTitle: "Budget and time",
    budgetLabel: "How much have you set aside for this piece?",
    budgetHelp: "It only helps us shape a better proposal.",
    timelineLabel: "When do you need it?",
    dateLabel: "Which date?",
    datePlaceholder: "e.g. 10 November, for a birthday",
    reviewTitle: "Before you send",
    reviewHelp: "One last look at your idea, and at what happens once you send it.",
    summaryTitle: "Your idea",
    summaryIdea: "Idea",
    summaryForm: "Form",
    summarySize: "Size",
    summaryColors: "Colours",
    summaryFidelity: "Fidelity",
    summaryBudget: "Budget",
    summaryTime: "Time",
    summaryEdit: "Edit",
    summaryNone: "—",
    attachPhotos: "{count} photo(s)",
    attachSketch: "sketch",
    attachVoice: "voice note",
    nextTitle: "What happens after you send it?",
    notesTitle: "Good to know",
    rulesLink: "All custom order notes",
    agree: "I have read and accept the custom order notes and terms.",
    agreeNote: "The version of the terms you accept today is saved with your order.",
    fullTerms: "Full custom-order terms",
    submit: "Send idea for review",
    submitNote: "Sending an idea is free; you only pay after you approve RAD’s proposal.",
    talkFirst: "Still not sure your idea is buildable?",
    talkFirstLink: "Talk to us first.",
    sentTitle: "Your request has reached RAD.",
    sentBody:
      "First we check whether the idea can be made; then we agree the price and exact timing with you.",
    sentFollow: "Follow your request",
    sentAnother: "Send another idea",
    cardForm: "Form",
    cardSize: "Size",
    cardBudget: "Budget",
    cardTime: "Time",
    cardFidelity: "Fidelity to reference",
    conceptForm: "Form",
    conceptSize: "Size",
    conceptColors: "Colours",
    conceptFidelity: "Fidelity to reference",
    conceptTime: "Time",
    conceptVoice: "A voice note is attached.",
    fallbackTitle: "Studio idea",
  },
} as const;

export type DesignerCopy = (typeof designerCopy)[keyof typeof designerCopy];
