export const trailCopy = {
  fa: {
    aria: "مسیر صفحه",
    home: "خانه",
    about: "درباره رَد",
    works: "آثار",
    qr: "کد QR",
    bag: "کیسه",
    checkout: "تسویه سفارش",
    favorites: "علاقه‌مندی‌ها",
    account: "حساب کاربری",
    accountInfo: "اطلاعات حساب",
    notifications: "اعلان‌ها",
    customOrders: "سفارش‌های اختصاصی",
    orders: "سفارش‌ها",
    order: "سفارش {id}",
    commission: "جزئیات سفارش",
    making: "مسیر ساخت",
    studio: "طراحی اختصاصی",
    shape: "رَد من چه شکلیه؟",
    workshop: "کارگاه هنرمند",
    differences: "موزه تفاوت‌ها",
    now: "امروز در کارگاه",
    reviews: "نظر مشتریان",
    help: "راهنما",
    version: "نسخهٔ {date}",
    contact: "تماس با رَد",
    design: "طراحی",
    cards: "کارت‌های اثر",
  },
  en: {
    aria: "Breadcrumb",
    home: "Home",
    about: "About RAD",
    works: "Works",
    qr: "QR code",
    bag: "Bag",
    checkout: "Checkout",
    favorites: "Favourites",
    account: "Account",
    accountInfo: "Account information",
    notifications: "Notifications",
    customOrders: "Custom orders",
    orders: "Orders",
    order: "Order {id}",
    commission: "Order details",
    making: "Making path",
    studio: "Custom design",
    shape: "What shape is my RAD?",
    workshop: "Artist workshop",
    differences: "Museum of differences",
    now: "Today in the workshop",
    reviews: "Customer reviews",
    help: "Help",
    version: "Version of {date}",
    contact: "Contact RAD",
    design: "Design",
    cards: "Product cards",
  },
} as const;

/** Home is the root of every trail, so it has nothing to show. */
export const TRAIL_HIDDEN_PATHS = ["/"];
