export const nowCopy = {
  fa: {
    lede: "از یک توده گل خام تا اثری که زندگی می‌کند. اینجا روند شکل‌گیری این کار را قدم‌به‌قدم می‌بینی.",
    heroAlt: "دست‌هایی که روی چرخ سفال به کاسه‌ای خام فرم می‌دهند",
    stagesTitle: "مسیر ساخت این کار",
    hereNow: "الآن اینجاست",
    upcoming: "در راه",
    done: "انجام شد",
    closeTitle: "رَد خودت را شروع کن",
    closeBody: "از یک عکس، یک فرم یا فقط یک حس. مسیر ساختش همین‌طور، قدم‌به‌قدم ثبت می‌شود.",
    closeCta: "شروع سفارش اختصاصی",
    indexLede: "رَدهایی که همین حالا در کارگاه ساخته می‌شوند؛ از ایده تا کوره آخر.",
    indexEmpty: "الآن کاری روی میز کارگاه نیست.",
    indexEmptyCta: "دیدن آثار آماده",
    stageOf: "مرحله‌ی {step} از {total}",
  },
  en: {
    lede: "From a lump of raw clay to a work that lives. Here you can follow this piece taking shape, step by step.",
    heroAlt: "Hands shaping a raw clay bowl on a potter's wheel",
    stagesTitle: "How this work is being made",
    hereNow: "It's here now",
    upcoming: "Coming",
    done: "Done",
    closeTitle: "Start your own RAD",
    closeBody: "From a photo, a form or just a feeling. Its making is recorded like this, step by step.",
    closeCta: "Start a custom piece",
    indexLede: "RADs being made in the workshop right now, from the idea to the last kiln.",
    indexEmpty: "Nothing is on the workshop table right now.",
    indexEmptyCta: "See available works",
    stageOf: "Stage {step} of {total}",
  },
} as const;
