const imageMeta = (alt: string, enAlt: string) => ({ alt, enAlt });

export const photoProducts = [
  {
    slug: "blue-pedestal-tray",
    vendorId: "artist-sahar",
    name: "سینی پایه‌دار آبی",
    subtitle: "لعاب آسمانی با خال‌خال",
    tomanPrice: 8_400_000,
    usdPrice: 97,
    color: "#6ba3c4",
    accent: "#c4956a",
    shape: "tall",
    category: "ceramics",
    status: "available",
    story:
      "ظرفی دوطبقه با لعاب آبی آسمانی و خال‌های قهوه‌ای؛ مناسب برای میوه خشک، جواهرات یا به‌عنوان آبجکت تزئینی.",
    details: ["ارتفاع ۲۴ سانتی‌متر", "استون‌ور لعاب‌دار", "دست‌ساز", "تنها یک نسخه"],
    images: [imageMeta("سینی پایه‌دار آبی", "Blue speckled pedestal tray")],
    en: {
      name: "Blue Pedestal Tray",
      subtitle: "Sky-blue speckled glaze",
      story:
        "A two-tier vessel in sky-blue glaze with brown speckles—ideal for dried fruit, jewellery, or as a decorative object.",
      details: ["24 cm high", "Glazed stoneware", "Handmade", "One of one"],
    },
  },
  {
    slug: "blue-pink-jar",
    vendorId: "artist-sahar",
    name: "قوطی آبی و صورتی",
    subtitle: "الگوی موجی دست‌نقاش",
    tomanPrice: 9_200_000,
    usdPrice: 106,
    color: "#f0e8dc",
    accent: "#2c4a8a",
    shape: "round",
    category: "ceramics",
    status: "available",
    story:
      "قوطی سفالی با درپوش آبی و بدنه‌ای تزئین‌شده با اشکال موجی آبی و صورتی؛ ترکیبی از ظرافت و جسارت رنگ.",
    details: ["ارتفاع ۱۸ سانتی‌متر", "سرامیک لعاب‌دار", "دست‌نقاش", "تنها یک نسخه"],
    images: [imageMeta("قوطی آبی و صورتی", "Blue and pink abstract jar")],
    en: {
      name: "Blue Pink Jar",
      subtitle: "Hand-painted wavy pattern",
      story:
        "A ceramic jar with a blue lid and a body decorated in blue and blush wavy shapes—a balance of delicacy and bold colour.",
      details: ["18 cm high", "Glazed ceramic", "Hand-painted", "One of one"],
    },
  },
  {
    slug: "cat-cup",
    vendorId: "artist-sahar",
    name: "فنجان گربه",
    subtitle: "دسته دم‌گونه",
    tomanPrice: 5_600_000,
    usdPrice: 65,
    color: "#d4b896",
    accent: "#1a1a1a",
    shape: "round",
    category: "ceramics",
    status: "available",
    story:
      "فنجانی سرامیکی با نقاشی گربه سیاه و دسته‌ای به‌شکل دم؛ اثری شوخ‌طبع و یکتا برای صبحانه یا میز کار.",
    details: ["ظرفیت ۲۵۰ میلی‌لیتر", "سرامیک لعاب‌دار", "ایمن برای مواد غذایی", "تنها یک نسخه"],
    images: [imageMeta("فنجان گربه", "Cat mug with tail handle")],
    en: {
      name: "Cat Cup",
      subtitle: "Tail-shaped handle",
      story:
        "A ceramic cup with a black cat illustration and a tail-shaped handle—a playful one-of-one for breakfast or a desk.",
      details: ["250 ml capacity", "Glazed ceramic", "Food safe", "One of one"],
    },
  },
  {
    slug: "contour-jar",
    vendorId: "artist-sahar",
    name: "قوطی خط‌کُنتور",
    subtitle: "الگوی عقیق سبز",
    tomanPrice: 10_800_000,
    usdPrice: 125,
    color: "#8a9a7b",
    accent: "#f0ece0",
    shape: "round",
    category: "ceramics",
    status: "available",
    story:
      "قوطی با بدنه‌ی موج‌دار و الگوی عقیق در طیف سبز و کرم؛ درپوشی سبز مریم‌گلی و سطحی براق و لمسی.",
    details: ["ارتفاع ۲۰ سانتی‌متر", "سرامیک لعاب‌دار", "بافت موج‌دار", "تنها یک نسخه"],
    images: [imageMeta("قوطی خط‌کُنتور", "Sage green contour jar")],
    en: {
      name: "Contour Jar",
      subtitle: "Agate-pattern glaze",
      story:
        "A jar with a wavy body and agate-like rings in sage and cream, topped with a sage-green lid and a glossy tactile surface.",
      details: ["20 cm high", "Glazed ceramic", "Wavy texture", "One of one"],
    },
  },
  {
    slug: "dachshund-sculpture",
    vendorId: "artist-sahar",
    name: "مجسمه داشهوند",
    subtitle: "سفال سیاه و سفید",
    tomanPrice: 7_200_000,
    usdPrice: 83,
    color: "#f5f0e8",
    accent: "#1a1a1a",
    shape: "wide",
    category: "sculpture",
    status: "available",
    story:
      "مجسمه‌ای مینیمال از سگ داشهوند با بدنه سفید، گوش‌های سیاه و خال‌های نامنظم؛ شوخ‌طبع و آرام‌کننده.",
    details: ["طول ۲۲ سانتی‌متر", "سرامیک لعاب‌دار", "قطعه تزئینی", "تنها یک نسخه"],
    images: [imageMeta("مجسمه داشهوند", "Ceramic dachshund figurine")],
    en: {
      name: "Dachshund Sculpture",
      subtitle: "Black and white ceramic",
      story:
        "A minimalist dachshund figurine with a white body, black ears, and irregular spots—playful and calming.",
      details: ["22 cm long", "Glazed ceramic", "Decorative piece", "One of one"],
    },
  },
  {
    slug: "olive-loop-vessel",
    vendorId: "artist-sahar",
    name: "ظرف حلقه‌ای زیتونی",
    subtitle: "لعاب خزه‌ای با خال",
    tomanPrice: 11_600_000,
    usdPrice: 134,
    color: "#6b7354",
    accent: "#8b5a3c",
    shape: "tall",
    category: "ceramics",
    status: "available",
    story:
      "ظرفی استوانه‌ای با دو حلقه‌ی دایره‌ای در بالا و لعاب زیتونی خزه‌ای؛ ترکیبی از مینیمالیسم و بافت دست‌ساز.",
    details: ["ارتفاع ۲۸ سانتی‌متر", "استون‌ور لعاب‌دار", "دست‌ساز", "تنها یک نسخه"],
    images: [imageMeta("ظرف حلقه‌ای زیتونی", "Olive green ring-handle vessel")],
    en: {
      name: "Olive Loop Vessel",
      subtitle: "Moss-green speckled glaze",
      story:
        "A cylindrical vessel with twin ring handles and a moss-green speckled glaze—minimal form with a handmade texture.",
      details: ["28 cm high", "Glazed stoneware", "Handmade", "One of one"],
    },
  },
  {
    slug: "blue-flower-portrait",
    vendorId: "artist-sahar",
    name: "گلدان پرتره گل‌دار",
    subtitle: "آبی روشن و طلایی",
    tomanPrice: 14_800_000,
    usdPrice: 171,
    color: "#a8c8d8",
    accent: "#c9a227",
    shape: "tall",
    category: "ceramics",
    status: "available",
    story:
      "گلدانی مجسمه‌وار به‌شکل پرتره با تاجی از گل‌های سرامیکی و یک شکوفه طلایی؛ اثری هنری و کاربردی.",
    details: ["ارتفاع ۳۲ سانتی‌متر", "سرامیک لعاب‌دار", "قطعه statement", "تنها یک نسخه"],
    images: [imageMeta("گلدان پرتره گل‌دار", "Floral crown head vase")],
    en: {
      name: "Blue Flower Portrait",
      subtitle: "Light blue and gold",
      story:
        "A sculptural portrait vase crowned with ceramic flowers and a single gold bloom—art object and functional vessel.",
      details: ["32 cm high", "Glazed ceramic", "Statement piece", "One of one"],
    },
  },
  {
    slug: "mint-angular-cup",
    vendorId: "artist-sahar",
    name: "فنجان مرمری نعنایی",
    subtitle: "فرم ارگانیک",
    tomanPrice: 5_800_000,
    usdPrice: 67,
    color: "#b8d4c8",
    accent: "#8ec4d4",
    shape: "round",
    category: "ceramics",
    status: "available",
    story:
      "فنجانی با فرم نامتقارن و لعاب مرمری سبز نعنایی و آبی آسمانی؛ دسته یکپارچه و طراحی ارگانیک.",
    details: ["ظرفیت ۲۸۰ میلی‌لیتر", "سرامیک لعاب‌دار", "فرم دست‌ساز", "تنها یک نسخه"],
    images: [imageMeta("فنجان مرمری نعنایی", "Organic marbled mint cup")],
    en: {
      name: "Mint Angular Cup",
      subtitle: "Organic marbled form",
      story:
        "An asymmetric cup in marbled mint and sky-blue glaze with an integrated handle—organic and one of one.",
      details: ["280 ml capacity", "Glazed ceramic", "Hand-built form", "One of one"],
    },
  },
  {
    slug: "orange-boat-sculpture",
    vendorId: "artist-sahar",
    name: "مجسمه قایق نارنجی",
    subtitle: "سبک folk art",
    tomanPrice: 12_400_000,
    usdPrice: 143,
    color: "#e87830",
    accent: "#f0e8dc",
    shape: "wide",
    category: "sculpture",
    status: "available",
    story:
      "قایق سرامیکی با شخصیت، پرندگان و دودکش نارنجی؛ می‌تواند گلدان کوچک یا آبجکت تزئینی باشد.",
    details: ["طول ۲۶ سانتی‌متر", "سرامیک لعاب‌دار", "دست‌ساز", "تنها یک نسخه"],
    images: [imageMeta("مجسمه قایق نارنجی", "Orange ceramic tugboat sculpture")],
    en: {
      name: "Orange Boat Sculpture",
      subtitle: "Folk-art style",
      story:
        "A ceramic tugboat with a figure, birds, and an orange smokestack—small vase or decorative object.",
      details: ["26 cm long", "Glazed ceramic", "Handmade", "One of one"],
    },
  },
  {
    slug: "spotted-loop-teapot",
    vendorId: "artist-sahar",
    name: "قوری حلقه‌ای خال‌دار",
    subtitle: "پاستلی و مجسمه‌وار",
    tomanPrice: 13_200_000,
    usdPrice: 153,
    color: "#f0ece8",
    accent: "#b8d4c8",
    shape: "round",
    category: "ceramics",
    status: "available",
    story:
      "قوری با دسته‌ی دایره‌ای بزرگ خال‌دار، دهانه صورتی و بدنه سفید-آبی؛ هم کاربردی و هم آبجکت هنری.",
    details: ["ظرفیت ۸۰۰ میلی‌لیتر", "سرامیک لعاب‌دار", "دست‌ساز", "تنها یک نسخه"],
    images: [imageMeta("قوری حلقه‌ای خال‌دار", "Pastel spotted loop teapot")],
    en: {
      name: "Spotted Loop Teapot",
      subtitle: "Pastel sculptural form",
      story:
        "A teapot with a large polka-dotted ring handle, pink spout, and blue-white body—functional and sculptural.",
      details: ["800 ml capacity", "Glazed ceramic", "Handmade", "One of one"],
    },
  },
  {
    slug: "mint-loop-vessel",
    vendorId: "artist-sahar",
    name: "ظرف حلقه‌ای نعنایی",
    subtitle: "لعاب خال‌دار سبز",
    tomanPrice: 10_200_000,
    usdPrice: 118,
    color: "#9ab89a",
    accent: "#8b5a3c",
    shape: "tall",
    category: "ceramics",
    status: "available",
    story:
      "ظرفی با حلقه‌ی دایره‌ای در بالا و لعاب سبز نعنایی خال‌دار؛ لبه‌ای با بافت کهنه و دست‌ساز.",
    details: ["ارتفاع ۲۶ سانتی‌متر", "استون‌ور لعاب‌دار", "دست‌ساز", "تنها یک نسخه"],
    images: [imageMeta("ظرف حلقه‌ای نعنایی", "Speckled sage loop vessel")],
    en: {
      name: "Mint Loop Vessel",
      subtitle: "Speckled sage glaze",
      story:
        "A vessel with a circular top handle and speckled sage glaze, with a weathered rim that feels handmade.",
      details: ["26 cm high", "Glazed stoneware", "Handmade", "One of one"],
    },
  },
  {
    slug: "speckled-cup",
    vendorId: "artist-sahar",
    name: "لیوان خال‌دار آبی",
    subtitle: "بدون دسته، مینیمال",
    tomanPrice: 4_800_000,
    usdPrice: 56,
    color: "#9ec4d8",
    accent: "#2a2a2a",
    shape: "round",
    category: "ceramics",
    status: "available",
    story:
      "لیوانی استوانه‌ای آبی آسمانی با خال‌های ریز سیاه؛ ساده، مدرن و مناسب نوشیدنی روزانه.",
    details: ["ظرفیت ۳۰۰ میلی‌لیتر", "سرامیک لعاب‌دار", "بدون دسته", "تنها یک نسخه"],
    images: [imageMeta("لیوان خال‌دار آبی", "Speckled blue tumbler")],
    en: {
      name: "Speckled Cup",
      subtitle: "Handleless minimal form",
      story:
        "A sky-blue tumbler with fine black speckles—simple, modern, and suited to everyday drinks.",
      details: ["300 ml capacity", "Glazed ceramic", "Handleless", "One of one"],
    },
  },
  {
    slug: "speckled-sculpted-mug",
    vendorId: "artist-sahar",
    name: "ماگ کدو خال‌دار",
    subtitle: "بافت شیاردار",
    tomanPrice: 5_400_000,
    usdPrice: 62,
    color: "#e8dcc8",
    accent: "#2a2a2a",
    shape: "round",
    category: "ceramics",
    status: "available",
    story:
      "ماگی با فرم کدو و شیارهای عمودی، رنگ کرم با خال‌های سیاه و لبه‌ای کمی نامنظم؛ حس wabi-sabi.",
    details: ["ظرفیت ۳۵۰ میلی‌لیتر", "سرامیک لعاب‌دار", "دسته C شکل", "تنها یک نسخه"],
    images: [imageMeta("ماگ کدو خال‌دار", "Speckled pumpkin mug")],
    en: {
      name: "Speckled Sculpted Mug",
      subtitle: "Fluted pumpkin form",
      story:
        "A pumpkin-shaped mug with vertical ridges, cream speckled glaze, and a slightly irregular rim—wabi-sabi character.",
      details: ["350 ml capacity", "Glazed ceramic", "C-shaped handle", "One of one"],
    },
  },
  {
    slug: "yellow-graphic-pitcher",
    vendorId: "artist-sahar",
    name: "پارچ زرد هندسی",
    subtitle: "الگوی chevron",
    tomanPrice: 9_800_000,
    usdPrice: 113,
    color: "#e8c830",
    accent: "#1a1a1a",
    shape: "tall",
    category: "ceramics",
    status: "available",
    story:
      "پارچی با لعاب زرد درخشان و الگوی هندسی chevron سیاه؛ دسته بزرگ و فرمی کمی نامتقارن.",
    details: ["ظرفیت ۱ لیتر", "سرامیک لعاب‌دار", "دست‌ساز", "تنها یک نسخه"],
    images: [imageMeta("پارچ زرد هندسی", "Yellow geometric ceramic pitcher")],
    en: {
      name: "Yellow Graphic Pitcher",
      subtitle: "Chevron pattern",
      story:
        "A pitcher in bright yellow glaze with a bold black chevron pattern and a large handle—slightly asymmetric form.",
      details: ["1 litre capacity", "Glazed ceramic", "Handmade", "One of one"],
    },
  },
];
