export const contactPageCopy = {
  fa: {
    titleLines: ["یه چیزی", "می‌خوای بپرسی؟"],
    ledeLines: ["درباره‌ی یه اثر، سفارش اختصاصی", "یا هر سؤالی که داری،", "این‌جا باهامون در ارتباط باش."],
    heroAlt: "لیوان سفالی دست‌ساز با لکه‌های لعاب سبز، روی لبه‌ای سنگی در نور عصر و سایه‌ی برگ‌ها",
    pathsTitle: "از کجا شروع کنیم؟",
    paths: {
      order: {
        title: "درباره‌ی سفارشم",
        body: "پرداخت، ارسال، وضعیت سفارش.",
        channel: "صفحه‌ی سفارش‌هات",
      },
      custom: {
        title: "سفارش اختصاصی",
        body: "قبل از سفارش چندتا سؤال دارم.",
        channel: "دایرکت اینستاگرام؛ عکس و طرحت رو همون‌جا بفرست",
      },
      other: {
        title: "سایر موضوعات",
        body: "سؤالی خارج از موارد بالا.",
        channel: "فرم پایین همین صفحه",
      },
      collaboration: {
        title: "همکاری",
        body: "پیشنهاد همکاری یا هر چیز دیگه.",
        channel: "فرم پایین همین صفحه",
      },
    },
    newTab: "(در زبانه‌ی تازه)",
    formTitle: "یا مستقیم پیام بذار",
    formLede: "هر وقت امکانش هست جواب می‌دیم.",
    directTitle: "مستقیم با رَد",
    instagramTitle: "مستقیم با رَد در ارتباط باش",
    instagramSub: "از طریق اینستاگرام سریع‌تر پاسخ می‌دیم.",
    instagramLabel: "دایرکت اینستاگرام رَد",
    emailTitle: "ایمیل به رَد",
    emailSub: "برای پیام‌های مفصل‌تر",
    emailSoon: "آدرس پس از فعال‌سازی",
    copyEmail: "کپی آدرس ایمیل",
    copied: "کپی شد",
    tipTitle: "یه نکته‌ی کوچیک",
    tipBody: "برای پیگیری سفارش، شماره‌ی سفارشت رو همراه پیام بنویس تا سریع‌تر پیداش کنیم.",
  },
  en: {
    titleLines: ["Something", "you want to ask?"],
    ledeLines: ["About a work, a custom piece,", "or any question you have —", "get in touch with us here."],
    heroAlt: "A handmade stoneware mug with green glaze spots on a stone ledge, in late sun and leaf shadow",
    pathsTitle: "Where should we start?",
    paths: {
      order: {
        title: "About my order",
        body: "Payment, shipping, order status.",
        channel: "Your orders page",
      },
      custom: {
        title: "A custom piece",
        body: "A few questions before I order.",
        channel: "Instagram Direct — send your photo or sketch there",
      },
      other: {
        title: "Something else",
        body: "A question outside the ones above.",
        channel: "The form on this page",
      },
      collaboration: {
        title: "Working together",
        body: "A collaboration idea, or anything like it.",
        channel: "The form on this page",
      },
    },
    newTab: "(opens in a new tab)",
    formTitle: "Or leave us a message",
    formLede: "We reply whenever we can.",
    directTitle: "Straight to RAD",
    instagramTitle: "Talk to RAD directly",
    instagramSub: "We answer faster on Instagram.",
    instagramLabel: "RAD on Instagram Direct",
    emailTitle: "Email RAD",
    emailSub: "For longer messages",
    emailSoon: "Address coming soon",
    copyEmail: "Copy email address",
    copied: "Copied",
    tipTitle: "A small tip",
    tipBody: "When asking about an order, include its order number so we can find it faster.",
  },
} as const;
