export const contactPageCopy = {
  fa: {
    title: "یه چیزی می‌خواستی بپرسی؟",
    lede: "درباره‌ی یه اثر، سفارشی که توی ذهنته یا سفارشی که ثبت کردی؛ از همین‌جا می‌تونیم حرف بزنیم.",
    human: "رَد یه کارگاه کوچیکه، نه مرکز تماس. پیامت رو یه آدم می‌خونه و خودش جواب می‌ده.",
    photoAlt: "دست‌هایی با گل روی پوست که لبه‌ی یک کاسه را روی چرخ سفال صاف می‌کنند",
    photoCaption: "از کارگاه",
    pathsTitle: "از کجا شروع کنیم؟",
    ideaTitle: "یه ایده دارم",
    ideaBody: "قبل از سفارش اختصاصی چندتا سؤال دارم.",
    ideaChannel: "توی دایرکت اینستاگرام؛ عکس و طرحت رو همون‌جا بفرست",
    orderTitle: "درباره‌ی سفارشم سؤال دارم",
    orderBody: "پرداخت، ارسال فیش، وضعیت ساخت یا تحویل.",
    orderChannel: "از صفحه‌ی همون سفارش؛ پیامت به سفارش وصل می‌شه",
    otherTitle: "یه حرف دیگه دارم",
    otherBody: "همکاری، پیشنهاد یا هر چیز دیگه.",
    otherChannel: "با فرم پایین همین صفحه",
    newTab: "(در زبانه‌ی تازه)",
    formTitle: "برامون پیام بذار",
    formLede: "هر وقت امکان صحبت مستقیم نداشتی، از اینجا بنویس. پیامت توی پنل رَد ثبت می‌شه و گم نمی‌شه.",
    directTitle: "مستقیم با رَد",
    instagramSub: "دایرکت اینستاگرام",
    open: "باز کردن",
    emailTitle: "ایمیل به رَد",
    emailSub: "برای پیام‌های مفصل‌تر",
    emailSoon: "آدرس پس از فعال‌سازی",
    tipTitle: "یه نکته‌ی کوچیک",
    tipBody: "برای پیگیری سفارش، شماره‌ی سفارش رو هم برامون بفرست تا سریع‌تر پیداش کنیم.",
  },
  en: {
    title: "Something you wanted to ask?",
    lede: "About a work, a piece you have in mind, or an order you have placed — we can talk right here.",
    human: "RAD is a small workshop, not a call centre. A person reads your message and answers it.",
    photoAlt: "Clay-covered hands smoothing the rim of a bowl on the potter's wheel",
    photoCaption: "From the workshop",
    pathsTitle: "Where should we start?",
    ideaTitle: "I have an idea",
    ideaBody: "I have a few questions before a custom order.",
    ideaChannel: "In Instagram Direct — send your photo or sketch there",
    orderTitle: "A question about my order",
    orderBody: "Payment, sending the receipt, making, or delivery.",
    orderChannel: "From that order's page — your message is linked to it",
    otherTitle: "Something else",
    otherBody: "Collaboration, a suggestion, or anything else.",
    otherChannel: "With the form on this page",
    newTab: "(opens in a new tab)",
    formTitle: "Leave us a message",
    formLede: "Whenever talking directly isn't possible, write here. Your message is saved in RAD's panel, so it won't get lost.",
    directTitle: "Straight to RAD",
    instagramSub: "Instagram Direct",
    open: "Open",
    emailTitle: "Email RAD",
    emailSub: "For longer messages",
    emailSoon: "Address coming soon",
    tipTitle: "A small tip",
    tipBody: "When asking about an order, include its order number so we can find it faster.",
  },
} as const;
