export const messageFormCopy = {
  fa: {
    topicLegend: "درباره‌ی چی می‌خوای حرف بزنیم؟",
    orderLabel: "شماره‌ی سفارش",
    orderHint: "اختیاری؛ همون شماره‌ای که بالای صفحه‌ی سفارش می‌بینی.",
    orderAttached: "این پیام به سفارش {id} وصل می‌شه.",
    subjectAttached: "اسم اثر ({subject}) هم کنار پیامت ثبت می‌شه.",
    subjectLine: "اثر: {subject}",
    contactLabel: "ایمیل یا شماره تماس",
    contactPlaceholder: "جایی که جوابت رو بفرستیم",
    contactOrderHint: "اختیاری؛ اگه خالی بمونه، به شماره‌ی ثبت‌شده در همین سفارش جواب می‌دیم.",
    bodyLabel: "پیامت",
    bodyPlaceholder: "هرچی می‌خوای بگو…",
    submit: "فرستادن پیام",
    sending: "در حال فرستادن…",
    replyNote: "در اولین فرصت جواب می‌دیم؛ ولی قول جواب فوری نمی‌دیم.",
    contactMissing: "یه ایمیل یا شماره بنویس تا بتونیم جوابت رو بدیم.",
    contactInvalid: "این شبیه ایمیل یا شماره تماس نیست؛ یه بار دیگه نگاهش کن.",
    bodyMissing: "پیامت خالیه؛ چند کلمه بنویس.",
    failed: "پیام فرستاده نشد. اتصال رو چک کن و دوباره بفرست؛ یا توی دایرکت بهمون بگو.",
    sentTitle: "پیامت رسید.",
    sentBody: "جوابت رو به {contact} می‌دیم.",
    sentBodyOrder: "جوابت رو به شماره‌ی ثبت‌شده در سفارش می‌دیم.",
    sentOrder: "به سفارش {id} وصل شد و کنار همون سفارش می‌بینیمش.",
    another: "یه پیام دیگه",
  },
  en: {
    topicLegend: "What would you like to talk about?",
    orderLabel: "Order number",
    orderHint: "Optional — the number shown at the top of your order page.",
    orderAttached: "This message will be linked to order {id}.",
    subjectAttached: "The work's name ({subject}) is saved with your message.",
    subjectLine: "Work: {subject}",
    contactLabel: "Email or phone",
    contactPlaceholder: "Where we should reply",
    contactOrderHint: "Optional — leave it empty and we'll reply to the phone number on this order.",
    bodyLabel: "Your message",
    bodyPlaceholder: "Say whatever you like…",
    submit: "Send message",
    sending: "Sending…",
    replyNote: "We reply as soon as we can, but we don't promise an instant answer.",
    contactMissing: "Add an email or phone number so we can reply.",
    contactInvalid: "That doesn't look like an email or phone number — take another look.",
    bodyMissing: "Your message is empty — write a few words.",
    failed: "The message didn't send. Check your connection and try again, or tell us in Instagram Direct.",
    sentTitle: "Your message arrived.",
    sentBody: "We'll reply to {contact}.",
    sentBodyOrder: "We'll reply to the phone number on your order.",
    sentOrder: "It's linked to order {id}, so we'll see it right beside that order.",
    another: "Send another",
  },
} as const;
