export const journeyCopy = {
  fa: {
    aria: "مسیرهای رَد",
    readyLine: "هر کدام، فقط یک‌بار.",
    tagMark: "رَد",
    customLine: ["با ایده‌ی شما،", "برای فضای شما."],
    customPhotoAlt: "دستی که طرح یک کوزه را با مداد روی کاغذ می‌کشد، کنار کاسه‌ای گلی",
    customSteps: ["گفتگو", "طراحی", "ساخت"],
    customStepsLabel: "سه قدم سفارش اختصاصی",
    railLabel: "مسیر ساخت این اثر",
    handsAlt: "دو دست خاک‌آلود که توده‌ای خاک رس را روی میز کارگاه ورز می‌دهند",
    handsNote: ["اثر دست", "ماده", "اتفاق"],
    aboutTitle: "رَد چیست؟",
    aboutStatement: "چیزی که بعد از دست، ماده و اتفاق باقی می‌ماند.",
    aboutLink: "داستان رَد",
  },
  en: {
    aria: "Ways into RAD",
    readyLine: "Each one, made only once.",
    tagMark: "RAD",
    customLine: ["From your idea,", "for your space."],
    customPhotoAlt: "A hand sketching a vase in pencil beside a small clay bowl",
    customSteps: ["Talk", "Design", "Make"],
    customStepsLabel: "Three steps of a custom order",
    railLabel: "This work's making path",
    handsAlt: "Two clay-dusted hands kneading a mound of clay on a workshop bench",
    handsNote: ["Hand", "Material", "Chance"],
    aboutTitle: "What is RAD?",
    aboutStatement: "What remains after the hand, the material, and chance.",
    aboutLink: "The RAD story",
  },
} as const;
