import type { ArtworkRecord } from "./type";
import { careFor, t } from "./copy";

/** Works offered in the shop. Numbers are permanent; never renumber. */
export const catalogArtworks: ArtworkRecord[] = [
  {
    radNumber: 45,
    slug: "blue-pedestal-tray",
    artistId: "rad-studio",
    category: "ceramics",
    initialStatus: "available",
    price: 3500000,
    usdPrice: 41,
    year: 2026,
    title: t("سینی پایه‌دار آبی", "Blue Pedestal Tray"),
    description: t("لعاب آسمانی با خال‌خال", "Sky-blue speckled glaze"),
    story: t(
      "ظرفی دوطبقه با لعاب آبی آسمانی و خال‌های قهوه‌ای؛ مناسب برای میوه خشک، جواهرات یا به‌عنوان آبجکت تزئینی.",
      "A two-tier vessel in sky-blue glaze with brown speckles—ideal for dried fruit, jewellery, or as a decorative object.",
    ),
    dimensions: t("ارتفاع ۲۴ سانتی‌متر", "24 cm high"),
    materials: {
      body: t("استون‌ور لعاب‌دار", "Glazed stoneware"),
      surface: null,
      process: null,
    },
    care: careFor("ceramics"),
    color: "#6ba3c4",
    accent: "#c4956a",
    shape: "tall",
    images: [
      {
        src: "/catalog/photos/transparent/blue-pedestal-tray.webp",
        alt: "سینی پایه‌دار آبی",
        enAlt: "Blue speckled pedestal tray",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 28,
    slug: "blue-pink-jar",
    artistId: "rad-studio",
    category: "ceramics",
    initialStatus: "available",
    price: 3000000,
    usdPrice: 35,
    year: 2026,
    title: t("قوطی آبی و صورتی", "Blue Pink Jar"),
    description: t("الگوی موجی دست‌نقاش", "Hand-painted wavy pattern"),
    story: t(
      "قوطی سفالی با درپوش آبی و بدنه‌ای تزئین‌شده با اشکال موجی آبی و صورتی؛ ترکیبی از ظرافت و جسارت رنگ.",
      "A ceramic jar with a blue lid and a body decorated in blue and blush wavy shapes—a balance of delicacy and bold colour.",
    ),
    dimensions: t("ارتفاع ۱۸ سانتی‌متر", "18 cm high"),
    materials: {
      body: t("سرامیک لعاب‌دار", "Glazed ceramic"),
      surface: t("دست‌نقاش", "Hand-painted"),
      process: null,
    },
    care: careFor("ceramics"),
    color: "#f0e8dc",
    accent: "#2c4a8a",
    shape: "round",
    images: [
      {
        src: "/catalog/photos/transparent/blue-pink-jar.webp",
        alt: "قوطی آبی و صورتی",
        enAlt: "Blue and pink abstract jar",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 57,
    slug: "cat-cup",
    artistId: "rad-studio",
    category: "ceramics",
    initialStatus: "available",
    price: 2000000,
    usdPrice: 24,
    year: 2026,
    title: t("فنجان گربه", "Cat Cup"),
    description: t("دسته دم‌گونه", "Tail-shaped handle"),
    story: t(
      "فنجانی سرامیکی با نقاشی گربه سیاه و دسته‌ای به‌شکل دم؛ اثری شوخ‌طبع و یکتا برای صبحانه یا میز کار.",
      "A ceramic cup with a black cat illustration and a tail-shaped handle—a playful one-of-one for breakfast or a desk.",
    ),
    dimensions: t("ظرفیت ۲۵۰ میلی‌لیتر", "250 ml capacity"),
    materials: {
      body: t("سرامیک لعاب‌دار", "Glazed ceramic"),
      surface: null,
      process: null,
    },
    care: t(
      "ایمن برای مواد غذایی. با دست بشویید؛ از شوک حرارتی دور بماند.",
      "Food safe. Hand wash; keep away from thermal shock.",
    ),
    color: "#d4b896",
    accent: "#1a1a1a",
    shape: "round",
    images: [
      {
        src: "/catalog/photos/transparent/cat-cup.webp",
        alt: "فنجان گربه",
        enAlt: "Cat mug with tail handle",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 30,
    slug: "contour-jar",
    artistId: "rad-studio",
    category: "ceramics",
    initialStatus: "available",
    price: 3200000,
    usdPrice: 38,
    year: 2026,
    title: t("قوطی خط‌کُنتور", "Contour Jar"),
    description: t("الگوی عقیق سبز", "Agate-pattern glaze"),
    story: t(
      "قوطی با بدنه‌ی موج‌دار و الگوی عقیق در طیف سبز و کرم؛ درپوشی سبز مریم‌گلی و سطحی براق و لمسی.",
      "A jar with a wavy body and agate-like rings in sage and cream, topped with a sage-green lid and a glossy tactile surface.",
    ),
    dimensions: t("ارتفاع ۲۰ سانتی‌متر", "20 cm high"),
    materials: {
      body: t("سرامیک لعاب‌دار", "Glazed ceramic"),
      surface: t("بافت موج‌دار", "Wavy texture"),
      process: null,
    },
    care: careFor("ceramics"),
    color: "#8a9a7b",
    accent: "#f0ece0",
    shape: "round",
    images: [
      {
        src: "/catalog/photos/transparent/contour-jar.webp",
        alt: "قوطی خط‌کُنتور",
        enAlt: "Sage green contour jar",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 58,
    slug: "dachshund-sculpture",
    artistId: "rad-studio",
    category: "sculpture",
    initialStatus: "available",
    price: 3500000,
    usdPrice: 41,
    year: 2026,
    title: t("مجسمه داشهوند", "Dachshund Sculpture"),
    description: t("سفال سیاه و سفید", "Black and white ceramic"),
    story: t(
      "مجسمه‌ای مینیمال از سگ داشهوند با بدنه سفید، گوش‌های سیاه و خال‌های نامنظم؛ شوخ‌طبع و آرام‌کننده.",
      "A minimalist dachshund figurine with a white body, black ears, and irregular spots—playful and calming.",
    ),
    dimensions: t("طول ۲۲ سانتی‌متر", "22 cm long"),
    materials: {
      body: t("سرامیک لعاب‌دار", "Glazed ceramic"),
      surface: null,
      process: null,
    },
    care: careFor("sculpture"),
    color: "#f5f0e8",
    accent: "#1a1a1a",
    shape: "wide",
    images: [
      {
        src: "/catalog/photos/transparent/dachshund-sculpture.webp",
        alt: "مجسمه داشهوند",
        enAlt: "Ceramic dachshund figurine",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 32,
    slug: "olive-loop-vessel",
    artistId: "rad-studio",
    category: "ceramics",
    initialStatus: "available",
    price: 4000000,
    usdPrice: 47,
    year: 2026,
    title: t("ظرف حلقه‌ای زیتونی", "Olive Loop Vessel"),
    description: t("لعاب خزه‌ای با خال", "Moss-green speckled glaze"),
    story: t(
      "ظرفی استوانه‌ای با دو حلقه‌ی دایره‌ای در بالا و لعاب زیتونی خزه‌ای؛ ترکیبی از مینیمالیسم و بافت دست‌ساز.",
      "A cylindrical vessel with twin ring handles and a moss-green speckled glaze—minimal form with a handmade texture.",
    ),
    dimensions: t("ارتفاع ۲۸ سانتی‌متر", "28 cm high"),
    materials: {
      body: t("استون‌ور لعاب‌دار", "Glazed stoneware"),
      surface: null,
      process: null,
    },
    care: careFor("ceramics"),
    color: "#6b7354",
    accent: "#8b5a3c",
    shape: "tall",
    images: [
      {
        src: "/catalog/photos/transparent/olive-loop-vessel.webp",
        alt: "ظرف حلقه‌ای زیتونی",
        enAlt: "Olive green ring-handle vessel",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 33,
    slug: "blue-flower-portrait",
    artistId: "rad-studio",
    category: "ceramics",
    initialStatus: "available",
    price: 4500000,
    usdPrice: 53,
    year: 2026,
    title: t("گلدان پرتره گل‌دار", "Blue Flower Portrait"),
    description: t("آبی روشن و طلایی", "Light blue and gold"),
    story: t(
      "گلدانی مجسمه‌وار به‌شکل پرتره با تاجی از گل‌های سرامیکی و یک شکوفه طلایی؛ اثری هنری و کاربردی.",
      "A sculptural portrait vase crowned with ceramic flowers and a single gold bloom—art object and functional vessel.",
    ),
    dimensions: t("ارتفاع ۳۲ سانتی‌متر", "32 cm high"),
    materials: {
      body: t("سرامیک لعاب‌دار", "Glazed ceramic"),
      surface: null,
      process: null,
    },
    care: careFor("ceramics"),
    color: "#a8c8d8",
    accent: "#c9a227",
    shape: "tall",
    images: [
      {
        src: "/catalog/photos/transparent/blue-flower-portrait.webp",
        alt: "گلدان پرتره گل‌دار",
        enAlt: "Floral crown head vase",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 34,
    slug: "mint-angular-cup",
    artistId: "rad-studio",
    category: "ceramics",
    initialStatus: "available",
    price: 2000000,
    usdPrice: 24,
    year: 2026,
    title: t("فنجان مرمری نعنایی", "Mint Angular Cup"),
    description: t("فرم ارگانیک", "Organic marbled form"),
    story: t(
      "فنجانی با فرم نامتقارن و لعاب مرمری سبز نعنایی و آبی آسمانی؛ دسته یکپارچه و طراحی ارگانیک.",
      "An asymmetric cup in marbled mint and sky-blue glaze with an integrated handle—organic and one of one.",
    ),
    dimensions: t("ظرفیت ۲۸۰ میلی‌لیتر", "280 ml capacity"),
    materials: {
      body: t("سرامیک لعاب‌دار", "Glazed ceramic"),
      surface: null,
      process: null,
    },
    care: careFor("ceramics"),
    color: "#b8d4c8",
    accent: "#8ec4d4",
    shape: "round",
    images: [
      {
        src: "/catalog/photos/transparent/mint-angular-cup.webp",
        alt: "فنجان مرمری نعنایی",
        enAlt: "Organic marbled mint cup",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 35,
    slug: "orange-boat-sculpture",
    artistId: "rad-studio",
    category: "sculpture",
    initialStatus: "available",
    price: 4500000,
    usdPrice: 53,
    year: 2026,
    title: t("مجسمه قایق نارنجی", "Orange Boat Sculpture"),
    description: t("سبک folk art", "Folk-art style"),
    story: t(
      "قایق سرامیکی با شخصیت، پرندگان و دودکش نارنجی؛ می‌تواند گلدان کوچک یا آبجکت تزئینی باشد.",
      "A ceramic tugboat with a figure, birds, and an orange smokestack—small vase or decorative object.",
    ),
    dimensions: t("طول ۲۶ سانتی‌متر", "26 cm long"),
    materials: {
      body: t("سرامیک لعاب‌دار", "Glazed ceramic"),
      surface: null,
      process: null,
    },
    care: careFor("sculpture"),
    color: "#e87830",
    accent: "#f0e8dc",
    shape: "wide",
    images: [
      {
        src: "/catalog/photos/transparent/orange-boat-sculpture.webp",
        alt: "مجسمه قایق نارنجی",
        enAlt: "Orange ceramic tugboat sculpture",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 36,
    slug: "spotted-loop-teapot",
    artistId: "rad-studio",
    category: "ceramics",
    initialStatus: "available",
    price: 4000000,
    usdPrice: 47,
    year: 2026,
    title: t("قوری حلقه‌ای خال‌دار", "Spotted Loop Teapot"),
    description: t("پاستلی و مجسمه‌وار", "Pastel sculptural form"),
    story: t(
      "قوری با دسته‌ی دایره‌ای بزرگ خال‌دار، دهانه صورتی و بدنه سفید-آبی؛ هم کاربردی و هم آبجکت هنری.",
      "A teapot with a large polka-dotted ring handle, pink spout, and blue-white body—functional and sculptural.",
    ),
    dimensions: t("ظرفیت ۸۰۰ میلی‌لیتر", "800 ml capacity"),
    materials: {
      body: t("سرامیک لعاب‌دار", "Glazed ceramic"),
      surface: null,
      process: null,
    },
    care: careFor("ceramics"),
    color: "#f0ece8",
    accent: "#b8d4c8",
    shape: "round",
    images: [
      {
        src: "/catalog/photos/transparent/spotted-loop-teapot.webp",
        alt: "قوری حلقه‌ای خال‌دار",
        enAlt: "Pastel spotted loop teapot",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 37,
    slug: "mint-loop-vessel",
    artistId: "rad-studio",
    category: "ceramics",
    initialStatus: "available",
    price: 3800000,
    usdPrice: 45,
    year: 2026,
    title: t("ظرف حلقه‌ای نعنایی", "Mint Loop Vessel"),
    description: t("لعاب خال‌دار سبز", "Speckled sage glaze"),
    story: t(
      "ظرفی با حلقه‌ی دایره‌ای در بالا و لعاب سبز نعنایی خال‌دار؛ لبه‌ای با بافت کهنه و دست‌ساز.",
      "A vessel with a circular top handle and speckled sage glaze, with a weathered rim that feels handmade.",
    ),
    dimensions: t("ارتفاع ۲۶ سانتی‌متر", "26 cm high"),
    materials: {
      body: t("استون‌ور لعاب‌دار", "Glazed stoneware"),
      surface: null,
      process: null,
    },
    care: careFor("ceramics"),
    color: "#9ab89a",
    accent: "#8b5a3c",
    shape: "tall",
    images: [
      {
        src: "/catalog/photos/transparent/mint-loop-vessel.webp",
        alt: "ظرف حلقه‌ای نعنایی",
        enAlt: "Speckled sage loop vessel",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 38,
    slug: "speckled-cup",
    artistId: "rad-studio",
    category: "ceramics",
    initialStatus: "available",
    price: 2000000,
    usdPrice: 24,
    year: 2026,
    title: t("لیوان خال‌دار آبی", "Speckled Cup"),
    description: t("بدون دسته، مینیمال", "Handleless minimal form"),
    story: t(
      "لیوانی استوانه‌ای آبی آسمانی با خال‌های ریز سیاه؛ ساده، مدرن و مناسب نوشیدنی روزانه.",
      "A sky-blue tumbler with fine black speckles—simple, modern, and suited to everyday drinks.",
    ),
    dimensions: t("ظرفیت ۳۰۰ میلی‌لیتر", "300 ml capacity"),
    materials: {
      body: t("سرامیک لعاب‌دار", "Glazed ceramic"),
      surface: null,
      process: null,
    },
    care: careFor("ceramics"),
    color: "#9ec4d8",
    accent: "#2a2a2a",
    shape: "round",
    images: [
      {
        src: "/catalog/photos/transparent/speckled-cup.webp",
        alt: "لیوان خال‌دار آبی",
        enAlt: "Speckled blue tumbler",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 39,
    slug: "speckled-sculpted-mug",
    artistId: "rad-studio",
    category: "ceramics",
    initialStatus: "available",
    price: 2000000,
    usdPrice: 24,
    year: 2026,
    title: t("ماگ کدو خال‌دار", "Speckled Sculpted Mug"),
    description: t("بافت شیاردار", "Fluted pumpkin form"),
    story: t(
      "ماگی با فرم کدو و شیارهای عمودی، رنگ کرم با خال‌های سیاه و لبه‌ای کمی نامنظم؛ حس wabi-sabi.",
      "A pumpkin-shaped mug with vertical ridges, cream speckled glaze, and a slightly irregular rim—wabi-sabi character.",
    ),
    dimensions: t("ظرفیت ۳۵۰ میلی‌لیتر", "350 ml capacity"),
    materials: {
      body: t("سرامیک لعاب‌دار", "Glazed ceramic"),
      surface: null,
      process: null,
    },
    care: careFor("ceramics"),
    color: "#e8dcc8",
    accent: "#2a2a2a",
    shape: "round",
    images: [
      {
        src: "/catalog/photos/transparent/speckled-sculpted-mug.webp",
        alt: "ماگ کدو خال‌دار",
        enAlt: "Speckled pumpkin mug",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 40,
    slug: "yellow-graphic-pitcher",
    artistId: "rad-studio",
    category: "ceramics",
    initialStatus: "available",
    price: 3500000,
    usdPrice: 41,
    year: 2026,
    title: t("پارچ زرد هندسی", "Yellow Graphic Pitcher"),
    description: t("الگوی chevron", "Chevron pattern"),
    story: t(
      "پارچی با لعاب زرد درخشان و الگوی هندسی chevron سیاه؛ دسته بزرگ و فرمی کمی نامتقارن.",
      "A pitcher in bright yellow glaze with a bold black chevron pattern and a large handle—slightly asymmetric form.",
    ),
    dimensions: t("ظرفیت ۱ لیتر", "1 litre capacity"),
    materials: {
      body: t("سرامیک لعاب‌دار", "Glazed ceramic"),
      surface: null,
      process: null,
    },
    care: careFor("ceramics"),
    color: "#e8c830",
    accent: "#1a1a1a",
    shape: "tall",
    images: [
      {
        src: "/catalog/photos/transparent/yellow-graphic-pitcher.webp",
        alt: "پارچ زرد هندسی",
        enAlt: "Yellow geometric ceramic pitcher",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 59,
    slug: "cobalt-ripple-tray",
    artistId: "rad-studio",
    category: "ceramics",
    initialStatus: "available",
    price: 4800000,
    usdPrice: 56,
    year: 2026,
    title: t("سینی موج کبالت", "Cobalt Ripple Tray"),
    description: t(
      "لعاب کبالت ترک‌ریز و دسته‌های حلقه‌ای",
      "Crazed cobalt glaze and loop handles",
    ),
    story: t(
      "سینی کم‌عمقی با لبه موج‌دار و دو دسته حلقه‌ای؛ لعاب کبالت در کف اثر با شبکه‌ای از ترک‌های ریز روشن می‌شود.",
      "A shallow tray with a rippled rim and two loop handles; fine pale crazing animates the deep cobalt glazed centre.",
    ),
    dimensions: t("قطر تقریبی ۳۲ سانتی‌متر", "Approximately 32 cm wide"),
    materials: {
      body: t("استون‌ور لعاب‌دار", "Glazed stoneware"),
      surface: null,
      process: null,
    },
    care: careFor("ceramics"),
    color: "#142e88",
    accent: "#e7e0d2",
    shape: "wide",
    images: [
      {
        src: "/catalog/photos/transparent/cobalt-ripple-tray.webp",
        alt: "نمای روبه‌روی سینی موج کبالت",
        enAlt: "Front view of the Cobalt Ripple Tray",
      },
      {
        src: "/catalog/photos/transparent/cobalt-ripple-tray-2.webp",
        alt: "نمای بالا از سینی موج کبالت",
        enAlt: "Top view of the Cobalt Ripple Tray",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 42,
    slug: "pink-petal-cup",
    artistId: "rad-studio",
    category: "ceramics",
    initialStatus: "available",
    price: 2400000,
    usdPrice: 28,
    year: 2026,
    title: t("فنجان گلبرگ صورتی", "Pink Petal Cup"),
    description: t(
      "فرم گلبرگی و دسته زیتونی",
      "Petal form with an olive handle",
    ),
    story: t(
      "فنجانی دست‌ساخت با دیواره‌هایی شبیه گلبرگ و دسته حلقه‌ای زیتونی؛ تفاوت‌های ظریف سطح، رد انگشت و قلم را نگه داشته‌اند.",
      "A hand-built cup with petal-like walls and an olive loop handle; subtle surface variations preserve the touch of hand and brush.",
    ),
    dimensions: t("ظرفیت تقریبی ۲۵۰ میلی‌لیتر", "Approximately 250 ml"),
    materials: {
      body: t("سرامیک لعاب‌دار", "Glazed ceramic"),
      surface: null,
      process: null,
    },
    care: careFor("ceramics"),
    color: "#eab9b6",
    accent: "#68723c",
    shape: "round",
    images: [
      {
        src: "/catalog/photos/transparent/pink-petal-cup.webp",
        alt: "فنجان گلبرگ صورتی با دسته زیتونی",
        enAlt: "Pink Petal Cup with olive loop handle",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 43,
    slug: "cobalt-fold-bowl",
    artistId: "rad-studio",
    category: "ceramics",
    initialStatus: "available",
    price: 4200000,
    usdPrice: 49,
    year: 2026,
    title: t("کاسه چین کبالت", "Cobalt Fold Bowl"),
    description: t(
      "لبه آزاد و لعاب آبی عمیق",
      "Free-folded rim and deep blue glaze",
    ),
    story: t(
      "کاسه‌ای پیکره‌وار با لبه آزاد و چین‌خورده؛ بیرون شیری و درون با لعاب کبالت عمیق پوشیده شده است.",
      "A sculptural bowl with a freely folded rim, creamy exterior, and a deep cobalt glazed interior.",
    ),
    dimensions: t("قطر تقریبی ۳۰ سانتی‌متر", "Approximately 30 cm wide"),
    materials: {
      body: t("استون‌ور لعاب‌دار", "Glazed stoneware"),
      surface: null,
      process: null,
    },
    care: careFor("ceramics"),
    color: "#102a8a",
    accent: "#eee6d9",
    shape: "wide",
    images: [
      {
        src: "/catalog/photos/transparent/cobalt-fold-bowl.webp",
        alt: "نمای روبه‌روی کاسه چین کبالت",
        enAlt: "Front view of the Cobalt Fold Bowl",
        spots: [
          { x: 68, y: 71, span: 0.12, material: t("استون‌ور", "Stoneware") },
        ],
        marks: [
          {
            x: 26,
            y: 42,
            title: t("لبه‌ی آزاد", "Free rim"),
            note: t(
              "چین‌ها آزادند؛ هیچ دو موجی یکسان نیست.",
              "Folded freely; no two waves match.",
            ),
          },
          {
            x: 58,
            y: 49,
            title: t("لعاب کبالت", "Cobalt glaze"),
            note: t(
              "آبی عمیق، سراسر درون کاسه.",
              "Deep blue across the whole interior.",
            ),
          },
          {
            x: 36,
            y: 73,
            title: t("فرم پیکره‌وار", "Sculptural form"),
            note: t("بیرونِ شیری استون‌ور.", "A creamy stoneware exterior."),
          },
        ],
      },
      {
        src: "/catalog/photos/transparent/cobalt-fold-bowl-2.webp",
        alt: "نمای بالا از کاسه چین کبالت",
        enAlt: "Top view of the Cobalt Fold Bowl",
        spots: [
          {
            x: 46,
            y: 50,
            span: 0.5,
            material: t("لعاب کبالت", "Cobalt glaze"),
          },
        ],
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 27,
    slug: "red-vessel-27",
    artistId: "artist-sahar",
    category: "ceramics",
    initialStatus: "available",
    price: 4500000,
    usdPrice: 53,
    year: 2026,
    title: t("کوزه‌ی سرخ شماره ۲۷", "Red Vessel No. 27"),
    description: t("لعاب خاکستر و اکسید آهن", "Ash glaze and iron oxide"),
    story: t(
      "ردّ حرکت دست روی این کوزه حفظ شده است؛ خطی که از دهانه آغاز می‌شود و در آتش به رنگ خاک گرم درآمده.",
      "The movement of the hand remains visible on this vessel—a line beginning at the rim and turning warm earth-red in the fire.",
    ),
    dimensions: t("ارتفاع ۳۸ سانتی‌متر", "38 cm high"),
    materials: {
      body: t("استون‌ور با پخت ۱۲۳۰ درجه", "Stoneware fired at 1230°C"),
      surface: null,
      process: null,
    },
    care: careFor("ceramics"),
    color: "#9f4030",
    accent: "#ead9bd",
    shape: "tall",
    images: [
      {
        alt: "نمای روبه‌روی کوزه سرخ",
        enAlt: "Front view of the red vessel",
        color: "#9f4030",
        accent: "#ead9bd",
        shape: "tall",
      },
      {
        alt: "نمای کناری کوزه سرخ",
        enAlt: "Side view of the red vessel",
        color: "#87382c",
        accent: "#ead9bd",
        shape: "tall",
      },
      {
        alt: "جزئیات لعاب کوزه سرخ",
        enAlt: "Red vessel glaze detail",
        color: "#ad4b38",
        accent: "#f0dfc2",
        shape: "round",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 46,
    slug: "olive-memory",
    artistId: "artist-sahar",
    category: "ceramics",
    initialStatus: "available",
    price: 4000000,
    usdPrice: 47,
    year: 2026,
    title: t("حافظه‌ی زیتونی", "Olive Memory"),
    description: t("لعاب مات و خاک نخودی", "Matte glaze and buff clay"),
    story: t(
      "فرمی آرام و متراکم برای شاخه‌های کوتاه؛ سطح مات آن نور را نگه می‌دارد و با گذر روز تغییر می‌کند.",
      "A quiet, compact form for short branches. Its matte surface holds the light and changes throughout the day.",
    ),
    dimensions: t("ارتفاع ۲۶ سانتی‌متر", "26 cm high"),
    materials: {
      body: t("خاک نخودی ایران", "Iranian buff clay"),
      surface: t("لعاب دست‌ساز مات", "Handmade matte glaze"),
      process: null,
    },
    care: careFor("ceramics"),
    color: "#4b513c",
    accent: "#dbc7a5",
    shape: "round",
    images: [
      {
        alt: "نمای روبه‌روی حافظه زیتونی",
        enAlt: "Front view of Olive Memory",
        color: "#4b513c",
        accent: "#dbc7a5",
        shape: "round",
      },
      {
        alt: "جزئیات لعاب زیتونی",
        enAlt: "Olive glaze detail",
        color: "#5c634a",
        accent: "#e0ceb0",
        shape: "wide",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 47,
    slug: "lut-line",
    artistId: "artist-sahar",
    category: "ceramics",
    initialStatus: "available",
    price: 4000000,
    usdPrice: 47,
    year: 2026,
    title: t("خطِ لوت", "Lut Line"),
    description: t("پرسلان و لعاب شنی", "Porcelain and sand glaze"),
    story: t(
      "لبه‌ای نامتقارن و خطی سرخ که مسیر باد روی شن را به یاد می‌آورد؛ ظرفی میان شیء روزمره و مجسمه.",
      "An asymmetric rim and red line recall wind moving across sand—a vessel between everyday object and sculpture.",
    ),
    dimensions: t("عرض ۴۵ سانتی‌متر", "45 cm wide"),
    materials: {
      body: t("پرسلان تقویت‌شده", "Reinforced porcelain"),
      surface: t("لعاب شنی", "Sand glaze"),
      process: null,
    },
    care: careFor("ceramics"),
    color: "#e6d8bd",
    accent: "#9e3d2d",
    shape: "wide",
    images: [],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 48,
    slug: "night-clay",
    artistId: "artist-sahar",
    category: "ceramics",
    initialStatus: "sold",
    price: 4000000,
    usdPrice: 47,
    year: 2026,
    title: t("خاکِ شب", "Night Clay"),
    description: t("لعاب مشکی نیمه‌براق", "Semi-gloss black glaze"),
    story: t(
      "سطح تیره و دهانه‌ی روشن این اثر، تضاد کوره در شب و خاک تازه را ثبت می‌کند.",
      "Its dark surface and bright rim record the contrast between a kiln at night and freshly worked clay.",
    ),
    dimensions: t("ارتفاع ۳۲ سانتی‌متر", "32 cm high"),
    materials: {
      body: t("سرامیک", "Ceramic"),
      surface: t("لعاب چندلایه", "Layered glaze"),
      process: null,
    },
    care: careFor("ceramics"),
    color: "#28231f",
    accent: "#c8a77b",
    shape: "tall",
    images: [],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 49,
    slug: "pomegranate-bowl",
    artistId: "artist-sahar",
    category: "ceramics",
    initialStatus: "available",
    price: 4000000,
    usdPrice: 47,
    year: 2026,
    title: t("کاسه‌ی انار", "Pomegranate Bowl"),
    description: t("لعاب قرمز مسی", "Copper-red glaze"),
    story: t(
      "کاسه‌ای برای مرکز میز، با فرورفتگی‌های کوچک که نور را مثل دانه‌های انار تقسیم می‌کنند.",
      "A centrepiece bowl with small impressions that divide the light like pomegranate seeds.",
    ),
    dimensions: t("قطر ۳۰ سانتی‌متر", "30 cm diameter"),
    materials: {
      body: t("سرامیک", "Ceramic"),
      surface: t("لعاب قرمز مسی", "Copper-red glaze"),
      process: null,
    },
    care: t("ایمن برای مواد غذایی. با دست بشویید.", "Food safe. Hand wash."),
    color: "#a23b32",
    accent: "#f0dfc2",
    shape: "round",
    images: [],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 50,
    slug: "white-silence",
    artistId: "artist-arman",
    category: "sculpture",
    initialStatus: "sold",
    price: 4500000,
    usdPrice: 53,
    year: 2026,
    title: t("سکوتِ سفید", "White Silence"),
    description: t("پرسلان بدون لعاب", "Unglazed porcelain"),
    story: t(
      "یک فرم کم‌صدا با بافت خام؛ هر تغییر نور، برجستگی تازه‌ای روی سطح آن نشان می‌دهد.",
      "A quiet form with a raw texture; every change in light reveals a new rise on its surface.",
    ),
    dimensions: t("عرض ۳۷ سانتی‌متر", "37 cm wide"),
    materials: {
      body: t("پرسلان خام", "Raw porcelain"),
      surface: null,
      process: null,
    },
    care: careFor("sculpture"),
    color: "#f2ece0",
    accent: "#5d5b4c",
    shape: "wide",
    images: [],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 51,
    slug: "blue-window",
    artistId: "artist-niloofar",
    category: "painting",
    initialStatus: "available",
    price: 6000000,
    usdPrice: 71,
    year: 2026,
    title: t("پنجره‌ی آبی", "Blue Window"),
    description: t("اکریلیک و پاستل روی بوم", "Acrylic and pastel on canvas"),
    story: t(
      "سطحی از آبی‌های عمیق و خط‌های گرم که نور یک پنجره‌ی دور را ثبت می‌کند.",
      "Deep blues and warm lines hold the memory of light from a distant window.",
    ),
    dimensions: t("۷۰ × ۵۰ سانتی‌متر", "70 × 50 cm"),
    materials: {
      body: t("اکریلیک و پاستل", "Acrylic and pastel"),
      surface: t("بوم کشیده‌شده", "Stretched canvas"),
      process: null,
    },
    care: careFor("painting"),
    color: "#31534a",
    accent: "#d87855",
    shape: "wide",
    images: [
      {
        src: "/catalog/photos/transparent/blue-window.webp",
        alt: "نقاشی انتزاعی پنجره آبی در نور استودیو",
        enAlt: "Blue Window abstract painting in studio light",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 60,
    slug: "woven-garden",
    artistId: "artist-kimia",
    category: "textile",
    initialStatus: "available",
    price: 4000000,
    usdPrice: 47,
    year: 2026,
    title: t("باغِ بافته", "Woven Garden"),
    description: t(
      "نقاشی و سوزن‌دوزی روی کتان",
      "Painting and embroidery on linen",
    ),
    story: t(
      "خطوط رنگی و دوخت‌های آزاد، تصویری از باغی خیالی را روی پارچه می‌سازند.",
      "Painted lines and free stitches shape an imagined garden across natural cloth.",
    ),
    dimensions: t("۶۰ × ۴۰ سانتی‌متر", "60 × 40 cm"),
    materials: {
      body: t("کتان طبیعی", "Natural linen"),
      surface: t("رنگ پارچه و دوخت دستی", "Fabric paint and hand stitch"),
      process: null,
    },
    care: careFor("textile"),
    color: "#b86449",
    accent: "#e9d7b9",
    shape: "tall",
    images: [
      {
        src: "/catalog/photos/transparent/woven-garden.webp",
        alt: "دیوارکوب کتانی باغ بافته با دوخت دست",
        enAlt: "Woven Garden hand-embroidered linen wall hanging",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 53,
    slug: "walnut-tide",
    artistId: "artist-arman",
    category: "woodwork",
    initialStatus: "available",
    price: 4000000,
    usdPrice: 47,
    year: 2026,
    title: t("موجِ گردو", "Walnut Tide"),
    description: t("تراش دستی چوب گردو", "Hand-carved walnut"),
    story: t(
      "کاسه‌ای پیکره‌وار که رگه‌های طبیعی چوب، حرکت نرم لبه‌ی آن را ادامه می‌دهند.",
      "A sculptural bowl whose grain continues the soft movement of its rim.",
    ),
    dimensions: t("قطر ۳۴ سانتی‌متر", "34 cm diameter"),
    materials: {
      body: t("چوب گردوی یک‌تکه", "Single piece of walnut"),
      surface: t("پرداخت روغن طبیعی", "Natural oil finish"),
      process: null,
    },
    care: careFor("woodwork"),
    color: "#76523b",
    accent: "#d3ad7f",
    shape: "round",
    images: [
      {
        src: "/catalog/photos/transparent/walnut-tide.webp",
        alt: "کاسه گردوی دست‌تراش موج گردو",
        enAlt: "Walnut Tide hand-carved walnut bowl",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 54,
    slug: "silver-orbit",
    artistId: "artist-leila",
    category: "jewelry",
    initialStatus: "available",
    price: 3000000,
    usdPrice: 35,
    year: 2026,
    title: t("مدار نقره‌ای", "Silver Orbit"),
    description: t(
      "نقره دست‌ساز و عقیق سبز",
      "Handmade silver and green agate",
    ),
    story: t(
      "حلقه‌ای باز با سنگی کوچک که مانند نقطه‌ای در مدار فلز قرار گرفته است.",
      "An open circle holds a small stone like a point moving through a metal orbit.",
    ),
    dimensions: null,
    materials: {
      body: t("نقره ۹۲۵", "925 silver"),
      surface: t("عقیق سبز", "Green agate"),
      process: null,
    },
    care: careFor("jewelry"),
    color: "#b78945",
    accent: "#22483d",
    shape: "round",
    images: [
      {
        src: "/catalog/photos/transparent/silver-orbit.webp",
        alt: "انگشتر نقره دست‌ساز مدار نقره‌ای با عقیق سبز",
        enAlt: "Silver Orbit handmade silver ring with green agate",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 55,
    slug: "red-garden-print",
    artistId: "artist-niloofar",
    category: "print",
    initialStatus: "sold",
    price: 2500000,
    usdPrice: 29,
    year: 2026,
    title: t("باغ سرخ", "Red Garden"),
    description: t("لینوکات روی کاغذ پنبه‌ای", "Linocut on cotton paper"),
    story: t(
      "چاپی تک‌نسخه از گیاهان خیالی؛ هر خط با دست روی صفحه بریده و چاپ شده است.",
      "A unique print of imagined plants, carved and printed entirely by hand.",
    ),
    dimensions: t("۵۰ × ۳۵ سانتی‌متر", "50 × 35 cm"),
    materials: {
      body: t("چاپ لینوکات", "Linocut"),
      surface: t("کاغذ پنبه‌ای", "Cotton paper"),
      process: null,
    },
    care: careFor("print"),
    color: "#243e35",
    accent: "#b34b37",
    shape: "wide",
    images: [
      {
        src: "/catalog/photos/transparent/red-garden-print.webp",
        alt: "چاپ دستی لینوکات باغ سرخ روی کاغذ پنبه‌ای",
        enAlt: "Red Garden hand-pulled linocut on cotton paper",
      },
    ],
    passport: null,
    difference: null,
    owner: null,
  },
  {
    radNumber: 56,
    slug: "quiet-weight",
    artistId: "artist-arman",
    category: "sculpture",
    initialStatus: "available",
    price: 5000000,
    usdPrice: 59,
    year: 2026,
    title: t("وزنِ آرام", "Quiet Weight"),
    description: t("سنگ و برنج", "Stone and brass"),
    story: t(
      "تعادل یک حجم تیره روی خطی باریک از برنج؛ سکون اثر با نزدیک‌شدن بیننده تغییر می‌کند.",
      "A dark volume balances on a narrow brass line, changing as the viewer approaches.",
    ),
    dimensions: t("ارتفاع ۴۲ سانتی‌متر", "42 cm high"),
    materials: {
      body: t("سنگ تراش‌خورده و برنج", "Carved stone and brass"),
      surface: null,
      process: null,
    },
    care: careFor("sculpture"),
    color: "#4a5039",
    accent: "#d8c4a0",
    shape: "tall",
    images: [],
    passport: null,
    difference: null,
    owner: null,
  },
];
