export const differencePageCopy = {
  fa: {
    title: "تفاوت‌ها",
    lede: "هر اثر دست‌ساز، رد زمان، دست و ماده را با خود دارد. همین تفاوت‌هاست که آن را زنده و منحصربه‌فرد می‌کند.",
    heroAlt: "کاسه‌ی سفالی دست‌ساز با لعاب کرم، حوضچه‌های آبی و خال‌های سبز تیره، روی سنگ تراورتن در نور گرم عصر",
    tracesTitle: "سه ردی که هر اثر با خودش دارد",
    traces: {
      hand: {
        title: "رد دست",
        body: "رد انگشت، بافت دست و حرکت ابزار هیچ‌وقت کاملاً تکرار نمی‌شود. همین ردها امضای اثر هستند.",
        note: ["رد دست،", "امضای هر اثر"],
        alt: "دست سفالگر که دیواره‌ی کاسه‌ای خام را روی چرخ شکل می‌دهد",
      },
      material: {
        title: "ماده",
        body: "خاک، لعاب، چوب یا نخ؛ هر ماده رفتار خودش را دارد. در سفال، دمای کوره، جریان هوا و ترکیب لعاب رنگ‌ها و بافت‌هایی می‌سازند که تکرار نمی‌شوند.",
        note: ["رنگ و بافت،", "هر بار متفاوت"],
        alt: "نمای نزدیک سطح لعاب کرم با حوضچه‌های آبی و خال‌های زنگاری",
      },
      idea: {
        title: "ایده",
        body: "هر اثر از یک فکر، احساس یا لحظه شکل می‌گیرد. حتی اگر از یک نمونه الهام بگیرد، مسیر ساختش همیشه متفاوت است.",
        note: ["اول یک خیال،", "بعد یک شکل"],
        alt: "طرح مدادی یک کاسه روی کاغذ دست‌ساز با لبه‌ی ناصاف و یک مداد چوبی",
      },
    },
    journeyTitle: "از ماده تا خودِ رد",
    journeyLede: "یک مسیر واقعی، بدون تکرار.",
    journey: {
      clay: { title: "خاک", body: "هر تکه از خاک، داستان خودش را دارد.", alt: "گلوله‌ی خاک ورزداده روی میز کارگاه" },
      shape: { title: "شکل دادن", body: "با دست، نه با قالب.", alt: "دو دست گل‌آلود که خاک را روی چرخ سفالگری مرکز می‌کنند" },
      glaze: { title: "لعاب", body: "قلم‌مو هر بار جای دیگری می‌نشیند.", alt: "قلم‌مویی که لعاب آبی را روی کاسه‌ی بیسکویت می‌نشاند" },
      fire: { title: "پخت", body: "آتش، رنگ‌ها را غافلگیر می‌کند.", alt: "درون کوره‌ی آجری با ظرف‌های خام روی طبقه‌های نسوز" },
      rad: { title: "رد نهایی", body: "همه‌چیز کنار هم، ردی یکتا می‌سازد.", alt: "کاسه‌ی پخته‌شده با خال‌های آبی کنار یک شاخه‌ی خشک" },
    },
    compareTitle: "تفاوت با محصولات صنعتی",
    compareLede: "در ظاهر شاید شبیه باشند، اما در جزئیات همه‌چیز فرق می‌کند.",
    compare: {
      industrial: {
        label: "صنعتی",
        alt: "کاسه‌ی خاکستری یکدست و کاملاً قرینه‌ی کارخانه‌ای",
        points: ["تولید انبوه", "یکنواخت و بدون رد دست", "رنگ ثابت و یکدست", "بدون هویت شخصی", "بدون امضا"],
      },
      rad: {
        label: "دست‌ساز (رَد)",
        alt: "کاسه‌ی دست‌ساز کمی نامتقارن با لعاب کرم و خال‌های آبی",
        points: ["یک‌به‌یک و منحصربه‌فرد", "رد دست و بافت طبیعی", "تنوع رنگ و لعاب", "تصمیم و حس سازنده در اثر", "شماره‌ی ثبت و شناسنامه‌ی یکتا"],
      },
    },
    museumAlt: "چند کاسه‌ی دست‌ساز با شکل و لعاب متفاوت کنار هم روی سنگ",
    quoteLines: ["هیچ دو ردی", "یکی نیست."],
    worksLink: "دیدن آثار آماده",
    portraitJourneyTitle: "از توصیف تا رد",
    portraitJourneyLede: "چهار نسخه از یک اثر، کنار هم. فاصله‌ها پنهان نمی‌شوند.",
    portraitNoImage: "برای این مرحله عکسی ثبت نشده؛ رنگ‌های همین مرحله را می‌بینید.",
    permissionLabel: "اجازه‌ی غافلگیری:",
  },
  en: {
    title: "Differences",
    lede: "Every handmade work carries the trace of time, hand and material. Those differences are what keep it alive and one of a kind.",
    heroAlt: "A handmade stoneware bowl with cream glaze, blue pools and dark green speckles on travertine in warm late light",
    tracesTitle: "Three traces every work carries",
    traces: {
      hand: {
        title: "The hand",
        body: "A fingerprint, the grain of a palm, the pull of a tool: none of it ever repeats exactly. Those marks are the work's signature.",
        note: ["The hand,", "each work's signature"],
        alt: "A potter's hand shaping the wall of a raw bowl on the wheel",
      },
      material: {
        title: "Material",
        body: "Clay, glaze, wood or thread: every material behaves its own way. In ceramics, kiln heat, airflow and the glaze mix make colours and textures that never come back.",
        note: ["Colour and texture,", "different every time"],
        alt: "A close view of cream glaze with blue pools and rust speckles",
      },
      idea: {
        title: "The idea",
        body: "Every work starts from a thought, a feeling or a moment. Even when it borrows from a model, the way it gets made is always different.",
        note: ["First a thought,", "then a form"],
        alt: "A pencil sketch of a bowl on deckle-edged handmade paper beside a wooden pencil",
      },
    },
    journeyTitle: "From material to RAD",
    journeyLede: "One real path, never repeated.",
    journey: {
      clay: { title: "Clay", body: "Every piece of clay has its own story.", alt: "A wedged ball of clay on a workshop bench" },
      shape: { title: "Shaping", body: "By hand, not by mould.", alt: "Two clay-covered hands centring clay on a potter's wheel" },
      glaze: { title: "Glaze", body: "The brush lands somewhere new each time.", alt: "A brush dabbing blue glaze onto a bisque bowl" },
      fire: { title: "Firing", body: "Fire surprises the colours.", alt: "Inside a brick kiln, raw pots stacked on refractory shelves" },
      rad: { title: "The final trace", body: "Everything together makes one trace.", alt: "The fired bowl with blue speckles beside a dried sprig" },
    },
    compareTitle: "Unlike factory products",
    compareLede: "They might look alike, but in the details everything is different.",
    compare: {
      industrial: {
        label: "Factory-made",
        alt: "A flat grey, perfectly symmetrical factory bowl",
        points: ["Mass-produced", "Uniform, no trace of a hand", "One fixed colour", "No personal identity", "Unsigned"],
      },
      rad: {
        label: "Handmade (RAD)",
        alt: "A slightly off-balance handmade bowl in cream glaze with blue speckles",
        points: ["One of one", "Hand marks and natural texture", "Varied colour and glaze", "The maker's choices, in the work", "A registered number and record"],
      },
    },
    museumAlt: "Several handmade bowls, each a different shape and glaze, together on stone",
    quoteLines: ["No two traces", "are the same."],
    worksLink: "See ready works",
    portraitJourneyTitle: "From description to RAD",
    portraitJourneyLede: "Four versions of one work, side by side. The distances stay visible.",
    portraitNoImage: "No photograph was recorded for this stage; you are seeing its colours.",
    permissionLabel: "Surprise allowed:",
  },
} as const;
