export const pdpCopy = {
  fa: {
    breadcrumb: "مسیر صفحه",
    home: "خانه",
    byLine: "اثری از",
    studio: "استودیوی رَد",
    available: "موجود",
    soldNote: "این اثر فروخته شده و دوباره ساخته نمی‌شود.",
    qrCardBody: "برای مشاهده‌ی شناسنامه دیجیتال و اشتراک‌گذاری.",
    passportCardBody:
      "داستان، مراحل ساخت و شناسنامه‌ی این اثر را در گذرنامه‌اش ببینید.",
    passportAction: "مشاهده گذرنامه",
    similarTitle: "آثار مشابه",
    gallery: "تصاویر اثر",
    views: "نماهای اثر",
    view: "نما",
    plate: "نمای آرشیوی",
    previousView: "نمای قبلی",
    nextView: "نمای بعدی",
    oneOfOne: "۱ / ۱",
    aboutTitle: "درباره‌ی این اثر",
    specsTitle: "جزئیات اثر",
    specCategory: "دسته‌بندی",
    specMaterial: "ماده",
    specSurface: "سطح",
    specProcess: "ساخت",
    specSize: "ابعاد",
    specMaker: "سازنده",
    specMade: "زمان ساخت",
    specEdition: "شماره‌ی آرشیو",
    specDetail: "جزئیات",
    varianceTitle: "تفاوتی که ماند",
    handmadeTitle: "دست‌ساز",
    handmadeLines: ["لبه‌ها دقیقاً یکسان نیستند؛", "قرار هم نبود که باشند."],
    printOf: "نقش یکتای",
    stampOf: "مهر اثر",
    anatomyTitle: "آناتومی اثر",
    makingTitle: "مسیر ساخت",
    careTitle: "مراقبت از اثر",
    questionsTitle: "ارسال، بسته‌بندی و پرسش‌ها",
    ask: "سؤالی مانده؟ با ما حرف بزن",
    askLede: "پیام بفرستید یا در اینستاگرام بنویسید.",
    specsLede: "مواد، ابعاد و شناسنامه",
    aboutLede: "داستان و الهام",
    anatomyLede: "آنچه سازنده نشان داده",
    makingLede: "از گل تا کوره",
    careLede: "برای ماندگاری بیشتر",
    questionsLede: "هرچه پیش از سفارش باید بدانید",
    glazeNote:
      "لعاب این اثر با دست زده شده؛ تفاوت‌های جزئی رنگ و بافت طبیعی‌اند و بخشی از هویت اثر.",
    makerNote: "یادداشت سازنده",
  },
  en: {
    breadcrumb: "Breadcrumb",
    home: "Home",
    byLine: "A work by",
    studio: "RAD Studio",
    available: "Available",
    soldNote: "This work has been sold and will not be made again.",
    qrCardBody: "Open its digital record or share it.",
    passportCardBody:
      "The story, making and record of this work, in its passport.",
    passportAction: "View passport",
    similarTitle: "Similar works",
    gallery: "Work images",
    views: "Work views",
    view: "View",
    plate: "Archive view",
    previousView: "Previous view",
    nextView: "Next view",
    oneOfOne: "1 / 1",
    aboutTitle: "About this work",
    specsTitle: "Details",
    specCategory: "Category",
    specMaterial: "Material",
    specSurface: "Surface",
    specProcess: "Making",
    specSize: "Dimensions",
    specMaker: "Maker",
    specMade: "Made",
    specEdition: "Archive number",
    specDetail: "Detail",
    varianceTitle: "The difference that stayed",
    handmadeTitle: "Handmade",
    handmadeLines: [
      "The edges aren't exactly the same.",
      "They weren't supposed to be.",
    ],
    printOf: "The unique print of",
    stampOf: "Seal of",
    anatomyTitle: "Anatomy of the work",
    makingTitle: "The making",
    careTitle: "Caring for it",
    questionsTitle: "Shipping, packing and questions",
    ask: "Still wondering? Talk to us",
    askLede: "Send a message or write to us on Instagram.",
    specsLede: "Materials, size and record",
    aboutLede: "Story and inspiration",
    anatomyLede: "What the maker points out",
    makingLede: "From clay to kiln",
    careLede: "So it lasts",
    questionsLede: "What to know before you order",
    glazeNote:
      "The glaze on this work was laid by hand; small shifts in colour and texture are natural and part of who it is.",
    makerNote: "Maker's note",
  },
} as const;
